### ISSUE TITLE
BrokenRulesCollection Not Working on Parent even though it Works on Child

### ISSUE THREAD

**Issue by MarkOverstreet** [MarimerLLC/cslaforum#11]
This is probably something very easy but since this is my first project with CSLA.NET I'm sure I'm doing something wrong :)

I have an parent object 

Complaint : BusinessBase<Complaint>

and a child property defined as 

 private static readonly PropertyInfo<Claimant> claimantProperty                = RegisterProperty<Claimant>(c => c.Claimant, RelationshipTypes.Child);

When I set a FirstName property to invalid data on the Claimant object, the BrokenRulesCollection on that object (Complaint.Claimant.BrokenRulesCollection) has a count of 3 and has all my business rules that are broken as expected.  However, if I look at Complaint.BrokenRulesCollection it is empty?  Why?  I thought from reading the eBooks that if I defined the relationship as a child, the parent would contain all broken rules?  Am I missing something?

Thanks for any assistance.

Mark

**Comment by jonnybee** [comment]
You have misunderstood the business rule system. 

Each object maintains a set of broken rules for that instance and a propertychanged on a parent or child does NOT trigger the business rules of all children. You have to add code for this yourself in f.ex an override of PropertyHasChanged or ChildChanged event.

There is a static method: BusinessRules.GetAllBrokenRules(root) that will traverse the object structure from the supplied parent and return an aggregated tree structure (so that you may f.ex. present a tree-view with the broken rules). 

Jonny Bekkum

**Comment by MarkOverstreet** [comment]
Ok, thanks for clearing that up.  But this leads me to another question related to saving.   If I save the parent object, it does take into consideration that the parent object isn't valid to save if a child object has broken rules correct?

**Comment by ChristopherHlusak** [comment]
Correct.  If a parent is valid but its child is not valid you will notice that IsValid on the parent is false (preventing a successful save) but IsSelfValid on the parent is true (that the parent itself is valid).

**Comment by MarkOverstreet** [comment]
Ok thanks for confiming.  Back to the my original question.  I don't see a class called BrokenRules and I don't see a static method called GetAllBrokenRules.   I only have a BrokenRulesCollection class and that class does not contain this method.  Any ideas?

**Comment by MarkOverstreet** [comment]
Never mind, for some reason intellisense wasn't showing it to me but I found it at the following location:

Csla.Rules.BusinessRules.GetAllBrokenRules
