### ISSUE TITLE
Async/Await - UnitTest - ApplicationContext.User

### ISSUE THREAD

**Issue by keithdv** [MarimerLLC/cslaforum#111]
I cannot get the needed behavior from Csla.ApplicationContext.User in my unit test's using MSTEST. We're using a custom principal. What we're seeing is that it reverts back to WindowsPrincipal after an 'await Task' method. See attached sandbox application. The logic works correctly in WPF if Csla.Wpf is referenced. I have been researching this and tried all of the different SynchronizationContext approaches I can find. None of them lead to the right behavior. Even using the DispatcherSynchContext and referencing Csla.Wpf doesn't do the trick.

How do I get the same behavior as WPF in my unit tests so that I can test properly?

**Comment by keithdv** [comment]
Here's the code: https://github.com/keithdv/CslaAsyncAwait

**Comment by keithdv** [comment]
I also wanted to share an excellent article on the SynchronizationContext approaches I tried.

http://blogs.msdn.com/b/pfxteam/archive/2012/02/02/10263555.aspx

**Comment by rockfordlhotka** [comment]
`Csla.ApplicationContext.User` is (in most cases) just a wrapper over .NET's normal way of managing the current principal object. And outside of ASP.NET (such as in a unit test) this means the principal is attached to the current thread. Which poses its own problems as the unit test framework's thread moves between AppDomain boundaries.

But in the case of WPF it turns out that Microsoft (mistakenly imo) chose to reset the thread's principal aggressively - to what it was when the WPF app first started up. In other words, there's no way to actually _use_ the thread's principal in WPF because they keep resetting it - typically to `GenericPrincipal` of all the dumb things.

So years ago CSLA adopted an approach within WPF where the principal is maintained as a `static` global within the [ApplicationContext provider](https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Xaml.Shared/ApplicationContextManager.cs) found in `Csla.Xaml`. This makes it possible to actually change the principal value - and just as important - keep it consistent throughout the lifetime of the application. There's a side-effect in that the value becomes common across all threads in the app's AppDomain, but that's generally considered beneficial.

It turns out that when Silverlight and then WinRT and then UWP came along that Microsoft didn't provide any thread-based hook on which to store the current principal. In fact they don't have the _concept_ of a current principal on those platforms (which does puzzle me). So those platforms also use the `static` model - again from the `Csla.Xaml` assembly.

I'm pretty sure I discuss this in the _Using CSLA 4_ ebook series.

**Comment by rockfordlhotka** [comment]
In short - you need to provide an `IContextManager` implementation that maintains the `User` value like the WPF provider does.

**Comment by JasonBock** [comment]
One thought I had.... @keithdv could you look at what the type of `SynchronizationContext.Current` is in a WPF app, and use that type in your test? Set `Current` to an instance of that type for the lifetime of that test (you could use `Bind()` from my Spackle library to do this).

This is pure conjecture, I have no idea if this will work, so take it FWIW :)

**Comment by keithdv** [comment]
I had tried that @JasonBock in the sandbox application. It's DispatcherSynchronizationContext. But even using DispatcherSynchronizationContext and referencing Csla.Xaml the principal is still lost. I'm assuming Csla.Xaml doesn't inject the same logic for MsTest as it does for WPF. It'd be interesting to see what Csla.Xaml is doing and replicate that for MsTest. However we already have an IContextManager implementation that I can modify to get my unit tests working (I Think).

Thanks for your help @rockfordlhotka and @JasonBock !
