### ISSUE TITLE
Analyzer exception for EvaluatePropertiesForSimplicityAnalyzer

### ISSUE THREAD

**Issue by ValentijnMakkenze** [MarimerLLC/cslaforum#131]
Hi,

I upgraded one of out projects to CSLA-Core.4.6.300 and got this analyzer exception

Warning	AD0001	Analyzer 'Csla.Analyzers.EvaluatePropertiesForSimplicityAnalyzer' 
threw an exception of type 'System.NullReferenceException' 
with message 'Object reference not set to an instance of an object.'.

**Comment by rockfordlhotka** [comment]
Thanks for reporting this issue. Hopefully @JasonBock can shed some light on what might be happening.

**Comment by ValentijnMakkenze** [comment]
I got three distinct errors, I reported all three of them but you closed two, I'm not sure why?

**Comment by rockfordlhotka** [comment]
Sorry, thought they were duplicate posts :blush: 

Regardless, this is a forum, not our issue tracker, and they all seem thematically the same - having to do with analyzers.

**Comment by JasonBock** [comment]
For all three cases, I need the following information:

* Are you opening a specific file in your project that causes the analyzer and/or code fix to fail? If so, please post the contents of that file. If it's company-specific, you may need to alter the names of members in the file, but getting the structure of the code is critical in figuring out what the problem is.
* You can launch VS with the /log option (https://msdn.microsoft.com/en-us/library/ms241272.aspx). When the exception happens, you'll see an entry in the log file for that exception with a stack trace.

Unfortunately, debugging analyzers isn't an easy thing to do. If you can get me those two pieces of information that will help.

Regards,
Jason

**Comment by ValentijnMakkenze** [comment]
The exceptions do not mention a filename just the projectname, they happen when I open the solution and wait a while until all analyzers are finished

I've attached the VS log but I don't see any exceptions that are related to the analyzers
[ActivityLog.zip](https://github.com/MarimerLLC/cslaforum/files/118785/ActivityLog.zip)

**Comment by JasonBock** [comment]
The exceptions won't mention a file, that's the unfortunate part. It makes it very difficult to figure out where the problem is.

I looked through the log file - the only record that's an exception is 618. It starts with "Exception handling callback for OnAfterOpenProject", which sounds somewhat like the behavior you're seeing. But the stack trace doesn't mention anything with the Csla.Analyzers types. That doesn't mean our analyzers aren't the problem, or that this error record is related to the error you're seeing, but at this point I'm not sure where to continue.

I did notice in a project I'm working on that if I have an interface that desends from IBusinessObject and defines a DP operation (e.g. DataPortal_Create) one of the analyzers reports a warning but then the code fix throws an exception. I haven't been able to confirm it yet but my guess is that I'm not handling interfaces correctly with the warning to flag for public DP operations. This may not be one of the three issues you're seeing but check to see if you have that somewhere in your code.

**Comment by acgritt** [comment]
I have started to run into the same issue with v4.6.300.  The analyzer seems to fail with the same error as above when I run a build.  I am actually using the information provided in @JasonBock's blog post from a few years ago:[Abstractions In CSLA](http://magenic.com/Blog/Post/43/Abstractions-in-CSLA).  I also get the same message with the EvaluateManagedBackingFieldsAnalyzer.

**Comment by JasonBock** [comment]
@acgritt thanks. Does this happen with a particular file? If I had the code that causes the error that would help tremendously.

**Comment by acgritt** [comment]
@JasonBock currently I only have 2 business objects setup but I was seeing the issue when I just had the one.  However, I do have the base objects based on the blog post in the same project so I don't know if that is causing it as well.  I will try to put together a sample with it happening and attach it.  It may take a day or so for me to get the time to do so.

**Comment by JasonBock** [comment]
I talked to some folks at MS about this, and they've started an issue of their own to track:

https://github.com/dotnet/roslyn/issues/9706

I'd suggest you put your "yes I want this" commentary there. This isn't just for the CSLA analyzers; this is for any analyzer written in .NET. Unfortunately that doesn't help right now, so the best I can ask of anyone who runs into an analyzer is to try and put code into a separate project to try and isolate the code that causes the failure.

In the meantime I'll keep looking at the analyzer code and try to put more defense mechanism in to prevent crashes where applicable.

**Comment by acgritt** [comment]
@JasonBock I have attached a sample that the analyzer error is occurring as part of the build.  Unfortunately I had to stick the Zip file inside the Docx file because even though the message window says it supports Zip, it was saying it was a non-supported file format.  As such, open the Word Document and extract the Zip and within the Zip is the code.

[AnalyzerErrorSample.docx](https://github.com/MarimerLLC/cslaforum/files/173901/AnalyzerErrorSample.docx)

**Comment by JasonBock** [comment]
@acgritt thanks, I'll take a look at it and see what I find.

**Comment by JasonBock** [comment]
@acgritt OK, I'm able to create 2 errors from your project. Thanks! This is actually a good thing :). I'll dig into why they're occurring and hopefully provide a fix soon.

**Comment by JasonBock** [comment]
@acgritt I think I now know what's causing the issues.

One is that you're declaring properties with the new "=>" syntax that you can do in C#6. I completely forgot about this, and I'm not handling it right in my analyzers. The other is that you have a partial class (Borrower) that is confusing my analyzer in terms of where a property is defined given its location span and how large the current partial class definition is.

Tricky :)

Now that I have a good understanding of the issues I should be able to address. Thanks again for the sample, this has helped tremendously!

**Comment by acgritt** [comment]
@JasonBock that is great to hear.  We have been using the `partial` classes in most of our usage of CSLA as it has worked better than regions for delineating the location of Business Rules, Data Access and Command/Criteria objects that are all private to the main class.  Largely this has been a carry over from years gone by when we had done a silverlight project using CSLA and we had to separate out the Server side logic from the Silverlight shared logic, but it has still be of great use to us.

**Comment by JasonBock** [comment]
@acgritt agreed, and I definitely need to support that scenario.

**Comment by JasonBock** [comment]
These two issues should be resolved now. There may still be issues lurking with the analyzers but the project that @acgritt no longer gives me any issues. The fixes should be coming in 4.6.400
