### ISSUE TITLE
Assign events to the child collection 

### ISSUE THREAD

**Issue by ConstantinPatak** [MarimerLLC/cslaforum#142]
Hello everybody,

I am having a business object (ParentClass) which contains a list of child business objects (ChildrenCollection) which inherits from the BusinessListBase<ChildrenCollection, ChildrenClass>. What I am trying to achieve is to assign the CollectionChanged event to the list before any operation occurs. 

The main problem is that when I save the parent object the returned instance doesn't contain a collection with the event registered (parentClass = parentClass.Save()).

I have tried a lot of solution and the only one that works is to assign the events inside the server side methods (e.g. DataPortal_Fetch, DataPortal_Insert, DataPortal_Update). Even though this solution works in 1 tier deploy I am not sure if it will work in 3 tiers deploy. 

Can anyone help me to find a solution in this problem?

Thanks in advance

**Comment by jonnybee** [comment]
Have you tried to override the OnChildChanged event in parentClass.

**Comment by ConstantinPatak** [comment]
Hi jonny,

The OnChildChanged event doesn't work for my case, because after the save operation (parentClass = parentClass.Save()) I also want to assign the CollectionChanged event to an ObservableCollection that is not a business child collection.

So what I need is an method that executes right after the new business object returns to the client side. I found the OnDeserialized method that seems to work. But, the question is the following, is this method gets executed on the client side?


Thanks

**Comment by rockfordlhotka** [comment]
`OnDeserialized` is executed every time the object graph is deserialized.

The graph may be serialized from client to server (in which case it runs on the server). The graph may be serialized from server to client (in which case it runs on the client). The graph may be serialized as part of n-level undo or an explicit `Clone` operation (in which case it runs where that operation occurs).

**Comment by ConstantinPatak** [comment]
So is it a good decision to assign events in this method? Will the client always uses a business object that it has registered the events? And if so, where is the proper place to unregister the events in order to not have memory licks?

**Comment by rockfordlhotka** [comment]
It is probably fine to hook up event handlers on deserialization. CSLA does this internally.

There really is no place to deregister the events, and normally that shouldn't be an issue. An event is a reference from the event source to the event target - so from the object graph to your external code (whatever that might be). Your object graph is normally the source of a _lot_ of events for things like data binding and various other things. Those events are never deregistered - the whole thing gets cleaned up when the object graph is dereferenced and ultimately garbage collected.

If you review the examples in the _Using CSLA 4_ book for example, I discuss how the data portal serializes the graph from server to client (and visa versa), and how it is _expected_ that you'll dereference/discard the original graph once it has been serialized.

For example:
```
  obj = obj.Save();
```

For a brief shining moment you have two instances of the object graph - the one on which you call the `Save` method, and the one returned as a result of the method. In this code though, you clearly dereference the first one because the reference is replaced with the second one.

At some point in the future, because that first object graph is no longer referenced, the GC will clean it up, including any references _it_ holds to other objects (such as event handlers).

**Comment by ConstantinPatak** [comment]
Thanks a lot Rockfort for your help.
