### ISSUE TITLE
Child Objects

### ISSUE THREAD

**Issue by fujiiface** [MarimerLLC/cslaforum#179]
Hi all,

I'm pretty confused about how to access a child object from within its parent.  My team and I have implemented this in past releases (think 3.8 era) but it felt like a hack since we had to add a **`GetItem`** function to the BusinessListBase class so that we could pass in the identifier we wanted.  This basically looked like `Parent.Children.GetItem(id)`.  I'm pretty sure this was incorrect and abused the framework but it worked for us.

We're using 4.6.300 on a new project and I want to implement a Parent/Child object again but I want to do it the "right" way.  I've found that the Project Tracker sample can be somewhat confusing at times since it's handling a bunch of scenarios between Project, Assignment, and Resources.

My basic structure is a simple Parent object with a list of Child objects that can only be added via the Parent.  If the Parent/Child relationship is setup correctly, how do I access a specific child?  Based on the examples, all I get are **`Assign`**, **`Remove`**, **`Contains`**, and **`ContainsDeleted`**.

Some possibly helpful information:
- There is only one Parent so children do not have a ParentId associated with it but they do have a ChildId.
- We are using the DAL factory implementation with DTO objects in MVC 5 and Entity Framework 6.

If I need to provide source code I can.

Thanks in advance.

**Comment by MarkOverstreet** [comment]
I'm just starting my first project in CSLA.NET so I certainly don't know much about the framework yet but I did buy the books and have a part of my app working.  It is an imaging application and here is the design:

We have a ScannedDocument object with a property for all the document images. Pretty simple so it looks something like this...

ScannedDocument doc = await ScannedDocument.NewScannedDocumentAsync();

ScannedDocumentImage newImage = doc.Images.AddNew()
...
...
doc.Save();

So this is pretty much a parent (Document) and children (Images).  I can easily access a child by simply doing doc.Images[0] for example.   This is pretty basic so I guess if you could give me a better idea of what you are trying to accomplish, maybe I can help.

Thanks
Mark

**Comment by fujiiface** [comment]
Hi Mark, thanks for the response.

I'm basically trying to understand how I can access the child object by it's identifier since that's what is being passed between pages.

In our previous implementation, we would do the following: 

    doc.Images.GetItem(pImageId).Property1 = value1;
    doc.Images.GetItem(pImageId).Property2 = value2;
    doc.Images.GetItem(pImageId).Property3 = value3;
    doc.Save();

We had to add on the GetItem() function in order to enable this.  GetItem would go through the collection and look for the child object that had a matching identifier via LINQ.  This doesn't seem right to me since it has to go through the collection each time a property is set.

If I'm not mistaken, your example only gets the child by its index so does that mean you're passing the index instead of an identifier from list pages to edit pages when you want to edit child information?

I'm just trying to understand if that's the way it was meant to be done or if there's some functionality missing because I implemented wrong.

**Comment by MarkOverstreet** [comment]
Ah I see.  Yes, that is exactly what I am doing.   We have a screen that displays the document detail and also contains a grid that shows the image file names and has a "view" button.  When the user clicks the "view" button (through binding) we have a reference to the actual object in the Images property of the Document object and then we display it.  

I understand what you are saying because I used to use KeyedCollections and that collection type allowed me to access the object directly by the key.  Unfortunately, I don't see any other way for you to get that to work unless you create your own method (e.g GetItem).  If you didn't want to use Linq and wanted to get a faster lookup, I guess you could implement some type of dictionary and store the key and the object reference.  Then you could look up the item in the dictionary.   I just used the ConcurrentDictionary in a project and it worked well.
