### ISSUE TITLE
CSLA and SaaS Applications

### ISSUE THREAD

**Issue by RafaelJovel** [MarimerLLC/cslaforum#200]
Hello from New Zealand,

We are looking at using CSLA .NET to move an existing XAML windows based application into the cloud. Currently this application is not using CSLA; so the approach we are looking at taking is to first refactor CSLA into the application, and then make the necessary changes to turn it into a SaaS application. We have looked around for some guidance on this or known 'gotchas' of anyone having experience of using CSLA within a SaaS application but found none (Well, we found some articles in the previous forum but could not get to them as is was shutdown, and even google cache had not kept them).

Are there any issues that we should keep in mind?

Thanks
Future CSLA Aficionados

**Comment by tfreitasleal** [comment]
I looks like the old forums are down:(

**Comment by rockfordlhotka** [comment]
I'll look into it, though probably not until Sunday, as I am in meetings all day today and Saturday.

**Comment by rockfordlhotka** [comment]
Got it sorted - the C drive was full of inet log files - it is online now.

**Comment by rockfordlhotka** [comment]
Regarding the original question, the primary issue with SaaS is multi-tenant hosting, and that is something CSLA supports through the concept of rule sets. You can define different sets of rules on a per-tenant basis, and even load those rules from a database if necessary. Obviously there's some startup overhead in dynamically loading the rules, but any solution you come up with will require dynamic rules based on tenant, so this shouldn't be an unexpected cost.

Otherwise it is up to you to make sure your code is written properly to maintain isolation between tenants, and of course your database design needs to take that into account so you can make sure to always filter database interactions based on the current tenant.

**Comment by RafaelJovel** [comment]
Yes, multi-tenancy is something that we are discussing, I will look at rule sets and see how they fit in the patterns we are discussing.

Thanks for the comments and looking into the issue of the old forums.
I am sure we will be asking more questions in our future endeavours.

Thanks 
Rafael
