### ISSUE TITLE
Telerik grid databinding example

### ISSUE THREAD

**Issue by tonydrake** [MarimerLLC/cslaforum#202]
I've used the grid/csla with great success in an older CSLA application (3.6x)
I've now working on a CSLA app using the latest (4.6x ) - and I just can't get the thing to work: eg assume project tracker resource for projectlist out of the box:
   ```
 <CollectionViewSource x:Key="projectListViewSource" d:DesignSource="{d:DesignInstance my:ProjectList, CreateList=True}" />
    <CollectionViewSource x:Key="projectListModelViewSource" Source="{Binding Path=Model, Source={StaticResource projectListViewSource}}" />
    <CollectionViewSource x:Key="projectListItemListViewSource" Source="{Binding Path=ItemList, Source={StaticResource projectListViewSource}}" />
```

and example of something I tried:
    ItemsSource="{Binding Source={StaticResource projectListItemListViewSource} }

Telerik's control doesn't have a DataSource, but I remember getting it going about 6 years ago with CSLA 3.6...
BTW, got it working no problems with Infragistics's grid (DataSource="Binding Source={StaticResource projectListItemListViewSource}}"

**Comment by rockfordlhotka** [comment]
I have never used their control, so I can't speak to it directly.

CSLA implements the Microsoft-defined data binding interfaces and behaviors for every platform we support. It is up to any UI control vendors to do the same, and in that case everything should "just work".

The one big catch is that the transition from Windows Forms to WPF was messy (to say the least) because Microsoft requires a different collection base class for WinForms and a different one for WPF. So in CSLA you need to use the right collection base class depending on which UI technology you are using :(

To make that worse, some control vendors decided to make things "easier" for people by having their WPF controls _also_ support the WinForms legacy base class/interface. That's a _real_ mess because they trapped people in the old style even while the code was running in WPF.

I don't know if any of this is relevant to the control you are using, but that's the history of the matter.

**Comment by tsvideo** [comment]
I Get it working with Telerik Grids with Binding to CollectionViewSource.View
e.G. ItemsSource="{Binding PersonalListViewSource.View}"
