### ISSUE TITLE
UWP PropertyInfo 

### ISSUE THREAD

**Issue by halloween8** [MarimerLLC/cslaforum#210]
We have finished porting our app from XAML/C# Windows Store app to UWP , it was a challenge, but it compiles and the application runs.  HOWEVER :-)  On a page where we have a CSLA BusinessBase object that contains many properties, one called called PartGroupID, we also have a PropertyInfo in our XAML

 <csla:PropertyInfo x:Name="PartGroupIDPropertyInfo" Property="{Binding Part.PartGroupID}" />

Everything is good until we save and set the Part to Null, when that happens, we get an error like this one 
System.InvalidOperationException "Member not found on object (PartGroupId)"

   at Csla.Reflection.MethodCaller.GetCachedProperty(Type objectType, String propertyName)
   at Csla.Reflection.MethodCaller.CallPropertyGetter(Object obj, String property)
   at Csla.Xaml.PropertyInfo.UpdateState()
   at Csla.Xaml.PropertyInfo.SetSource(Object dataItem)
   at Csla.Xaml.PropertyInfo.SetSource(Boolean propertyValueChanged)
   at Csla.Xaml.PropertyInfo.<>c.<.cctor>b__68_0(DependencyObject o, DependencyPropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at Microsoft.Practices.Prism.Mvvm.BindableBase.OnPropertyChanged(String propertyName)
   at Microsoft.Practices.Prism.Mvvm.BindableBase.SetProperty[T](T& storage, T value, String propertyName)
   at Dealerlive.ViewModels.PartEditViewModel.set_Part(IPart value)

This part of the code didn't change, am I doing something wrong?

**Comment by rockfordlhotka** [comment]
Could be a bug in the UWP PropertyInfo implementation. It is mostly the same as WinRT, but there are some differences.

So your entire model gets set to `null`, or a bound child object, or ??

**Comment by halloween8** [comment]
The entire model gets set to null yes.

**Comment by rockfordlhotka** [comment]
Is the model bound direct to the XAML, or do you use a `ViewModelBase<T>` and bind to the `Model` property?

Basically what I'm asking is this: what is my shortest path to a repro of the issue?

**Comment by halloween8** [comment]
ill try to send you a sample

**Comment by halloween8** [comment]
I was able to replicate it in a sample app

https://1drv.ms/u/s!AuUgjHGDs33wj5lZxqm_xka4S0Xn6w

**Comment by halloween8** [comment]
Am I doing something different then everybody else or Am I using a functionally that nobody else use?

**Comment by MarceloJGaray** [comment]
Is not just on UWP. I updated a large WPF Solution to 4.6.4 and found the exact same issue. I throws the same error everywhere during initial UI databinding. I had to rollback to 4.6.301 because my application became unusable. All databinding is done through a ViewModelBase<T> and bind to the Model property.

**Comment by rockfordlhotka** [comment]
Thanks for these data points - I'll look at this as soon as I can, which is likely to be Wednesday given my work schedule.

**Comment by halloween8** [comment]
I Can confirm that going back to 4.6.301 did work, I no longer have the issue mentioned above

**Comment by rockfordlhotka** [comment]
I must thank you for helping to identify this issue - it turns out that it is a bug that's been there for a _very_ long time and nobody has encountered it until I did a recent change to `PropertyInfo` that (basically) accidentally revealed the problem.

The `PropertyInfo` control parses the binding expression to see if it has indirection (so like "Person.LastName" redirects from DataContext to Person, then to LastName). And it walks through the binding path to find the second-to-last node (in this example: Person) and _that_ is the actual data source object.

What has been happening all this time (unbeknownst to all of us) is that if the `Person` value is `null` then the actual data source object has been set to the parent viewmodel object - when it _should_ have been `null`.

**Comment by rockfordlhotka** [comment]
The [CSLA .NET 4.6.401 release](https://github.com/MarimerLLC/csla/releases/tag/v4.6.401) should resolve this issue.

**Comment by halloween8** [comment]
Great thanks, and I'm glad I was able to help somehow :-D
