### ISSUE TITLE
What did you do with some namespaces when porting existing CSLA.NET code to .NET Core?

### ISSUE THREAD

**Issue by lmsantin** [MarimerLLC/cslaforum#230]
I tried to rewrite an existing library to a new Class library (.NET Core).
I was not too easy for me as in http://www.lhotka.net/weblog/ReferencingCSLA46300FromASPNET5.aspx
I have several issues with references and missing namespaces like:

-System.Security.Permissions
-System.Runtime.Serialization
-System.ComponentModel.DataAnnotations ( I solved this one adding a package from NuGet)

Is CSLA.NET going to have a version for .NET Core?

**Comment by rockfordlhotka** [comment]
The current preview release in NuGet includes support for .NET Core (netstandard1.5), and so supports ASP.NET Core.

**Comment by lmsantin** [comment]
Thank you for response.

Didn't you have any issue using DisplayAttribute when porting classes to .NET Core?

Is there any sample?

**Comment by rockfordlhotka** [comment]
The trick with supporting ".NET Core" is to appreciate that this could mean supporting versions of netstandard from 1.0 to 1.6. 

There's a whole matrix of what is in or out (or different) in each version of netstandard, and of which platforms (UWP, .NET 4.6, .NET Core, etc.) that are supported by each version of netstandard.

CSLA will support netstandard 1.5, which is the release version of .NET Core, but which doesn't support a lot of the pre-existing platforms (like .NET, Xamarin, etc.).

(more accurately, .NET, Xamarin, etc. don't yet support netstandard 1.5, but that can (and maybe already has) changed)

I chose netstandard 1.5 because CSLA _already supports_ all the pre-existing platforms_, so I have no need for a netstandard version that supports Xamarin (for example). I just need to support .NET Core and ASP.NET Core - so 1.5 is perfect for that.

The advantage of choosing 1.5 over previous versions of netstandard, is that in 1.5 Microsoft provides NuGet packages for a lot of things, including `DataAnnotations`, and a somewhat better version of reflection than in the older netstandard versions.

So to your specific question about `DisplayAttribute`, because I targeted netstandard1.5 I don't need to do anything other than reference the existing official NuGet package for `DataAnnotations`.

**Comment by Bowman74** [comment]
If I'm reading this correctly, Xamarin now supports all versions of net standard: https://blog.xamarin.com/net-standard-library-support-for-xamarin/

Interestingly enough, it looks like UWP only supports up to 1.4.

**Comment by rockfordlhotka** [comment]
Ahh, good - things change so fast it is impossible to keep up - that's great news about Xamarin!

_Eventually_ I'll be able to drop everything except some version of netstandard, because eventually all platforms will support some (reasonably modern) version of netstandard. I really look forward to that day because I'll be able to remove tons of compiler directives from the CSLA codebase!

**Comment by lmsantin** [comment]
I referenced the existing official NuGet package for DataAnnotations and it solved my issue partially.
I am still having problems with:
System.Security.Permissions and System.Runtime.Serialization

**Comment by rockfordlhotka** [comment]
You do need to ensure the versions of the packages you bring in are compatible with the version of netstandard being used by your project.

You can see what I target with CSLA for netstandard1.5 by looking at `project.json`: https://github.com/MarimerLLC/csla/blob/master/Source/Csla.NetStandard1.x/project.json

This is (fortunately) temporary until the new tooling comes out later this year, and everything switches back to `csproj` files - but at the moment you need to learn all the ins and outs of `project.json` to work with any .NET Core stuff.

**Comment by lmsantin** [comment]
I tried with the same dependencies you have in https://github.com/MarimerLLC/csla/blob/master/Source/Csla.NetStandard1.x/project.json but I could not build my library.
I have some custom exception classes in my library. The all use the SecurityPermission attribute and receive a System.Runtime.Serialization.SerializationInfo object in GetObjectData method.

VS is not finding those types.
SecurityPermission is defined in System.Security.Permissions namespace.
SerializationInfo is defined in System.Runtime.Serialization namespace.

Both are located in mscorlib.dll

How can I add a reference to .NET Core to mscorlib.dll?

**Comment by rockfordlhotka** [comment]
There is no mscorlib in .NET Core - everything that used to be there now comes from various NuGet packages.

Are you starting with, or trying to use, the project templates in Visual Studio? I have found those to be pretty useless, because the VS tooling lags very far behind the .NET Core runtime (the runtime is released, the tooling is still very much prerelease).

You are better off, in general, using VS Code and the samples from http://asp.net to get started.

**Comment by rockfordlhotka** [comment]
One thing about `SerializationInfo` is that it is (at least in the context of CSLA) used by the `BinaryFormatter`, and that doesn't exist in .NET Core. You must use `MobileFormatter` for serialization, as it is the only serializer available in .NET Core that meets the needs of CSLA.

I think (you'd have to look at the CSLA code), that my custom exceptions all have compiler directives to skip compiling the code you refer to when building for netstandard.

**Comment by lmsantin** [comment]
You are right, I am using Class Library (.NET Core), a project template in Visual Studio. The library I tried to port is for a live application so I think I'd better wait for stable version of the platform.

Thank you Rocky for your time.

**Comment by rockfordlhotka** [comment]
The _platform_ itself is officially released and so should be fairly stable. The _tooling_ is problematic :cry: 

Some things (like BinaryFormatter and NDCS) may never come to .NET Core, so you'll almost certainly need to adjust your exception code (for example).

In CSLA I do this via compiler directives. All the code is in a shared project, and is then compiled into projects for each of the (now 11) different platforms I support.

Each project has its own compiler directive, such as NETSTANDARD, or UWP, etc. This way in my code I do things like:

```
#if NETSTANDARD
  // netstandard specific code goes here
#else
  // code for all other platforms goes here
#endif
```
