### ISSUE TITLE
WCF Data Portal - BusinessIdentity becomes GenericIdentity

### ISSUE THREAD

**Issue by bradtwurst** [MarimerLLC/cslaforum#235]
We are developing a WPF application built upon CSLA 4.6.x and we occasionally have the system get 'stuck' and the identity is no longer being resolved properly but instead is the GenericIdentity.

It is using the Wcf based data portal running on IIS on Windows Server 2012 R2.

We also have a custom BusinessIdentity and BusinessPrincipal

I have wrapped the Data Portal calls on the client side to validate that the Identity is the correct type

I've also added logic to DataPortal_Invoke and InvokeComplete methods to also validate that the Identity is the correct type.

I've walked through the DataPortal logic a bit for the WCF based data portal and I see where the Identity is extracted from the WCF csla service call
* Wcf method extracts context from request, 
* Wcf method calls DataPortal server method with context
* data portal server method calls setContext(context) .

I am not seeing how the the context could be lost as the system transfers from client to server.

The frustrating part is that this situation only happens once every two to five weeks and after the IIS service containing the wcf data portal is reset, the system functions as expected (business logic that failed works fine).

Also, once the server is reset, the client can usually continue without restarting as we are handling this exception on the client side so that the client doesn't crash completely.

It doesn't seem to matter the data portal method that is called (Fetch, Create, Update, ...) and I haven't been able to discern any pattern to when things start to fail. 

Can anyone offer a suggestion on what else to look at?

Thanks,
James

=================================================

The exception that we are getting is a DataPortal exception from the remote data portal

-----------------

```
Csla.DataPortalException: DataPortal.Fetch failed 
(Unable to cast object 
of type 'System.Security.Principal.GenericIdentity' 
to type 'IBusinessIdentity'.) 
---> 
Csla.Reflection.CallMethodException: ERList.DataPortal_Fetch method call failed 
---> 
System.InvalidCastException: 
Unable to cast object 
of type 'System.Security.Principal.GenericIdentity' 
to type 'IBusinessIdentity'.
   at Func.User() 
```

-----------------

The Func.User method is 
```c#
        public static IBusinessIdentity User()
        {
            return (IBusinessIdentity)Csla.ApplicationContext.User.Identity;
        }

```
-----------------

And the IBusinessIdentity interface

```c#
   public interface IBusinessIdentity: IIdentity
    {
        string Database { get; set; }
    }

```
and portions of the custom BusinessIdentity 

```c#
    [Serializable()]
    public class BusinessIdentity : CslaIdentityBase<BusinessIdentity>, IBusinessIdentity
    {

        public static readonly PropertyInfo<string> DatabaseProperty = RegisterProperty<string>(c => c.Database);
        public string Database { get { return ReadProperty(DatabaseProperty); } set { LoadProperty(DatabaseProperty, value); } }

	...
    }

```

and the main class definition of the custom BusinessPrincipal 

```c#
    [Serializable]
    public class BusinessPrincipal : CslaPrincipal
    {
	...
    }

```

The configuration for the data portal is

```xml
    <system.serviceModel>
        <client>
            <endpoint
                name="WcfDataPortal"
                address="http://server/DataPortal/WcfPortal.svc"
                binding="wsHttpBinding"
                bindingConfiguration="wsHttpBinding_IWcfPortal"
                contract="WcfPortal.IWcfPortal"
         />
        </client>
        <bindings>
            <wsHttpBinding>
                <binding name="wsHttpBinding_IWcfPortal" maxReceivedMessageSize="2147483647">
                    <security mode = "None"/>
                    <readerQuotas maxBytesPerRead="2147483647"
                                  maxArrayLength="2147483647"
                                  maxStringContentLength="2147483647"
                                  maxNameTableCharCount="2147483647"
                                  maxDepth="2147483647"/>
                </binding>
            </wsHttpBinding>
        </bindings>
    </system.serviceModel>

```

**Comment by rockfordlhotka** [comment]
The exception occurs on the server I assume? So the client somehow sends the wrong principal to the server and the server fails?

Like everyone, I hate these hard-to-repeat problems. Arg!

WPF doesn't help, because it tries to control the principal in a way that (imo) is basically useless for all real-world scenarios. So CSLA works to overcome the stupid WPF behaviors.

In short, WPF tries to make sure the principal can be set exactly _one time_ and that can only happen _as the application loads_. After that point it tries to reset the principal to that original value "on your behalf" as the process flow switches threads and in some other cases. So it is pretty much impossible to have a user log in or out of a running WPF app - I have no idea what the dev team was thinking when they did this to WPF.

To overcome this the `Csla.Xaml` assembly has an `ApplicationContextManager` that manages `Csla.ApplicationContext.User` as an AppDomain-level `static` value - totally ignoring the .NET "current principal" value since Microsoft rendered it useless. I talk about this in the [Using CSLA 4](http://store.lhotka.net/using-csla-4-all-books) ebook series.

I'm going through all this background in the hopes that it can help you isolate and identify what's happening in your particular case.

It _should be_ that the data portal gets the principal from that `static` value (via `Csla.ApplicationContext.User`) regardless of the thread or anything else on the WPF client - it is an AppDomain global value. This only works, of course, if your app includes a reference to `Csla.Xaml.dll`.

It should also be the case that the server gets the principal from the client as part of the request from the client. Barring you having configured the data portal to _not_ pass the principal from client to server by setting the data portal's authentication type to "Windows". But you don't show that in your config files, so that's not the case. (if you _had_ done such a thing it would be using the Windows domain identity on the server).

**Comment by rockfordlhotka** [comment]
The only way to get more detail on the client is to subclass `WcfProxy` - which isn't hard - and that would give you the ability to override some methods and perhaps add some logging before/after invoking the `base.Whaterver()` methods you override. Don't change the behavior - just add logging?

**Comment by bradtwurst** [comment]
I've wrapped both the WcfProxy and WcfPortal classes to capture more info and deployed the wrappers.

Of course, the situation has stopped occurring.

I'll re-open this issue if/when I have more info.

Thanks for the quick responses

**Comment by bradtwurst** [comment]
After a bit of trials and errors, (mostly errors), I've discovered the root cause (and it is us..)

The problem boiled down to a static member that was being populated with the results of a dataportal.fetch call which was being executed during the deserialization of the data in the wcf call.

As it was being populated during the deserialization, the ApplicationContext.User was not populated yet, which is where we were getting the connection name for the data query.

Thanks for the assistance and guidance.
