### ISSUE TITLE
How to make an OPTIONAL [EmailAddress] property?

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/cslaforum#245]
The following property declaration produces a broken rule: "The E-mail field is not a valid e-mail address" with an empty string as the value.

```
[EmailAddress]
[StringLength(255)]
[Display(ResourceType = typeof(StringsBiz), Name = "Email")]
public string Email
{
    get { return GetProperty(EmailProperty, m_email); }
    set { SetProperty(EmailProperty, ref m_email, value); }
}
```

I would have expected an empty string to be ignored, unless the property was `[Required]`.

In an ASP.NET MVC 5 app, the client side validation is passing with an empty string. However, in the POST, the object fails the `IsValid` check and returns the view, but the error is not shown in the validation summary.

Is there a workaround for this?

Thanks
Michael

**Comment by jonnybee** [comment]
There is 2 possible solutions for this. 

The standard DataAnnotations rule for EmailAddress doe NOT accept an empty string but it does however accept a null value. So one option is to make the property return null when the value is an empty string.

        public override bool IsValid(object value) {
            if (value == null) {
                return true;
            }

            string valueAsString = value as string;

            // Use RegEx implementation if it has been created, otherwise use a non RegEx version.
            ....

Another option is to add a "ShortCircuiting" rule in AddBusiness rules with a priority lower than 0 (to make it run before the DataAnnotation rules that will always have priority = 0). You _should_ also override ReadProperty to return the propertyvalue from the private field so that your business rules can get to the value without using the property getter. 

    public class StopIfEmpty : PropertyRule
    {
        public StopIfEmpty(IPropertyInfo primaryProperty)  : base(primaryProperty)
        {
            InputProperties.Add(primaryProperty);
        }
        protected override void Execute(RuleContext context)
        {
            var value = context.GetInputPropertyValue(PrimaryProperty)
            if (string.IsNullOrEmpty())
            {
                context.AddSuccessResult(true);
            }
        }
    }
 
And in AddBusinessRules

    BusinessRules.AddRule(new StopIfEmpty(EmailProperty) { Priority = -1 };

**Comment by michaelcsikos** [comment]
Thanks, Jonny. I've gone with your second option, as I've generally avoided null strings in CSLA objects since reading the 2005 book.

For anyone else who might be looking for this:

```
public class EmailAddressAllowEmptyString
    : PropertyRule
{
    public EmailAddressAllowEmptyString(PropertyInfo<string> primaryProperty)
        : base(primaryProperty)
    {
        InputProperties.Add(primaryProperty);
    }

    protected override void Execute(RuleContext context)
    {
        var value = context.GetInputValue<string>(PrimaryProperty);

        if (string.IsNullOrEmpty(value))
            context.AddSuccessResult(true);
    }
}

protected override void AddBusinessRules()
{
    base.AddBusinessRules();

    BusinessRules.AddRule(new EmailAddressAllowEmptyString(EmailProperty) { Priority = -1 });
}
```
