### ISSUE TITLE
DataPortal.Create<T>() questions

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#298]
Hi All,
I have a few questions regarding DataPortal.Create<T>() the way its used in sample code.

1) In some places we are calling DataPortal.Create from static methods and no implementation of Dataportal_Create which I understand that if you don't have to initialize the object we don't need the implementation but in other places we have implemented Dataportal_Create and it contains only one line
base.DataPortal_Create(); , why are we not consistent?

2) In EditableRoot with EditableChildlist, inside sometimes we call DataPortal.CreateChild<T>(); and in other places we don't?

kind regards

**Comment by tfreitasleal** [comment]
I was looking at some samples yesterday and noticed 1. above. I can't explain.

**Comment by rockfordlhotka** [comment]
I can answer 1 easily enough: sometimes I use (or create) the samples to test various aspects of CSLA as I'm building them. And sometimes I need to set a breakpoint in various places to ensure that the code executes as expected. As a result, the samples can have overloads like that, purely because this allows setting of a breakpoint in the debugger while I'm working.

You are right, that sort of thing should get cleaned up, but like everyone, I'm often pressed for time and don't go back through the code.

**Comment by Chicagoan2016** [comment]
Thank you Rocky,
For no.2 , i noticed that in sample project in EncapsulatedInokeDto, in OrderEdit.cs we are calling  DataPortal.CreateChild();  but not in SkillEditList.cs

Regards

**Comment by Chicagoan2016** [comment]
Rocky, I reread parts of Data Access book, I figured it out :),
Thanks you all for your help
