### ISSUE TITLE
Partial updates and CSLA

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#302]
In most of our applications we tend to do a lot of partial updates for business objects, If we use csla to implement our business objects how would we accomplish that? I saw an example of partial update in EncapsulatedinvokeDto sample, it's in OrdalDal.cs class and this partial update is called from ShipOrder method of the same class. It appears there is no way to call this partial update using the Business object.

I can't put my finger on it but somehow it doesn't seemed to be the most elegant approach compared to the rest of CSLA :), I feel like we could design partial updates better.
Any thoughts/suggestions will be appreciated.

Regards

**Comment by rockfordlhotka** [comment]
The challenge with using a diffgram instead of full serialization of the object graph is that you lose the advantages of mobile objects.

In other words, if you fully serialize an object graph from one device to another, then on the new device you can (and do) have a 100% clone of the object graph, so you are able to maintain and use code that is all in a single set of classes - by deploying the same DLL to both devices.

If you send only a diffgram from one device to another, then on the new device you do _not_ have any way to have a clone of the object graph. So you need to either define a whole new object graph to hydrate the diffgram, or just use the diffgram in a generic sense (as an XML or JSON object for example). In this context the new device must have a completely different (and probably duplicate) implementation of any business logic because you can not reuse the same classes.

There's also non-trivial complexity in round-tripping the diffgram. When any data comes back to the original device, that data needs to be merged back into the existing object graph. There's insufficient data to generate a new clone, so merging is the only option. _That_ requires that the diffgram and object graph both carry some sort of per-instance unique ID values so it is possible to match diffgram elements back to the original object instance. It also means the diffgram needs to include any "fix-up" information, such as indicating that an object instance needs to be removed from or added to the original object graph.

Not that this second model is _wrong_, but it has never been a design goal of CSLA.

There is a diffgram sample in the `Samples` folder that shows how to implement these concepts - sitting on top of CSLA as it is, with the addition of a unique per-instance ID, a visitor pattern for pulling and updating data from the original object graph, and a Command object used to implement all the "server side" code necessary to interact with the diffgram.

**Comment by rockfordlhotka** [comment]
For what it is worth, a small group of myself and some colleagues are discussing what CSLA would look like if it were started from scratch today (the [Ystari](https://github.com/MarimerLLC/Ystari) project), with current technologies and views on software. Having the diffgram concept be a first-class _option_ is definitely part of that conversation.

**Comment by Chicagoan2016** [comment]
Thank you for the insightful answer Rocky, I will look into the Diffgram sample.
kind regards
