### ISSUE TITLE
UWP, PCL (.net standard 1.4) and CSLA-Core 4.6.500 collide

### ISSUE THREAD

**Issue by Umplify** [MarimerLLC/cslaforum#313]
I have a solution with the following projects:

- .net standard 1.4 (Portable Class Library aka PCL)
- UWP (universal windows platform)

According to the [documentation found here](https://oren.codes/2016/07/09/using-xamarin-forms-with-net-standard/), the highest .net standard library that we can use to support UWP is .net standard 1.4. 

Now, I'd like to add one of the existing view models that I implemented in CSLA ver 4.6.500 but nuget package refuses it because csla-core needs minimum version of .net standard 1.6 not 1.4. 

What is the solution to be able to keep using csla view model that I've had and working in another project? I doubt if downgrading csla library is an option too as they do not support .net standard 1.4

**Comment by rockfordlhotka** [comment]
The NuGet package for CSLA includes support for UWP, and support for netstandard 1.5. It doesn't have support for netstandard 1.4, because that would have been a ton of work just to support UWP (which I already support directly).

My recommendation is to use Shared Projects to get your code to older compile targets like netstandard 1.0-1.4.

**Comment by Umplify** [comment]
Shared project is a great idea. thanks.
