### ISSUE TITLE
Plan for merging DataPortal Update results into existing graph

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#341]
The 4.6.600 release is nearly complete - a beta should go into NuGet this week - the big deal is support for netstandard, ASP.NET Core, and VS 2017.

So I'm planning the next big thing - and I want to tackle something that's been a recurring request since day 1 of CSLA .NET: having an option for the DataPortal to merge the results of an Update call (Save or SaveAsync) into the existing client-side object graph.

Today you have to rebind any UI to the result of the Save call

```c#
  // unbind the UI from the soon-to-be-old object graph
  obj = obj.Save();
  // rebind the UI to the new object graph
```
I chose this model for a couple reasons, not least of which is that I wanted to use Microsoft's serialization components (not write my own), and I didn't want to add arbitrary data to the round-tripped data stream.

Obviously over the years I've had to give up on Microsoft's serialization components because the BinaryFormatter and NDCS haven't been supported on all platforms starting in 2007 with Silverlight.

And really, the only "arbitrary data" that is required is a way to identify each object in the graph uniquely _within the graph_. This can be done with a simple numeric counter value, so we're not talking about any big addition to the datastream (not like a guid for example).

You might ask what's driving me to do this after all these years. Fair question 😄  The reason is that _today's_ style of app almost never has a Cancel button, and increasingly apps don't even have Save buttons for the user. Users expect that data will be saved automatically as the user leaves each screen (or even field, though that's a different matter). And this includes child objects being edited on child windows or overlays.

Building these types of UI (especially common on phones) is really hard if you have to unbind/rebind the object graph - because you might be triggering a save operation when the user leaves a child or grandchild editing screen - while currently not-visible screens still exist in the user's back history that are bound to the parent, child, or other higher level objects in the same object graph.

For those who've been arguing I should do this for the past many years, I will humbly accept your "I told you so" statements 😉 

I'll be tracking this work via this issue: https://github.com/MarimerLLC/csla/issues/712

**Comment by tonydrake** [comment]
Wonderful Rocky, I've building UI for WPF, UXP and phones using this
metaphor - no cancel, or save. (once you do it, you'll never go back to
'Cancel/Save') I'm happy with my workaround, but it's not perfect - but
once site effect on how I do it, I get a complete history of changes (I use
a CQRS like pattern).

Look forwards to my refactor in the future.

**Comment by jensbrand** [comment]
This will be excellent

**Comment by ajj7060** [comment]
I'm interested to see how this will turn out.  I'm glad its optional as well; while we're currently building out a mobile app using Xamarin.Forms, its only for select functionality, and our main application is going to be WinForms for a while.

Mobile being one of the factors is unexpected as well; we're binding all our XF to VMs (which subclass Csla.Xaml.ViewModel<T>) and so the VM itself is never rebound, just the Model property gets replaced, so the rebinding for us has been easier than in WinForms :-)

**Comment by tfreitasleal** [comment]
If I understand it correctly, when this feature is ready, we could use SaveUpdate/SaveUpdateAsync instead of the usual Save/SaveAsync, no matter the platform WindowsForms/WPF/Android, etc.
This makes Save/SaveAsync kind'a redundant.
I suppose the framework would continue to include these methods for compatibility sake.

**Comment by rockfordlhotka** [comment]
@tfreitasleal it is true that a new method is probably the way to go (rather than an overload). But as noted by @ajj7060, the existing model isn't really redundant, since it is obviously the model used by _everyone_ right now, and it won't be trivial to switch an app from the existing model to the new model.

**Comment by GillesBer** [comment]
This is promising. Getting a (lighter) subgraph over the network will improve the user perception (perf & latency).
This is what has blocked us from moving from a 2 tier to a 3 tier architecture: our 3 tiers test shown a huge impact on performances, because we have (win)forms with lots of tabs, so the impact on moving the 'entire' graph over the WAN is worse than doing a ADO.NET call over the WAN for a child objet!

Also +1 for using a new method: I don't want to confuse my team too much. And we need to integrate it progressively.

**Comment by ajj7060** [comment]
@GillesBer  I'm surprised by that; I had the exact opposite, I had to move to 3-tier because the database queries were too "chatty."  It might be worthwhile to check and see if all the parts of the graph really must be saved as a single unit of work.  

For example in a system I worked on, I realized that of course the order header and line items must always be part of the same UoW/transaction, but the order comments actually didn't need to be; I removed the OrderComments collection from the Order class and made OrderComments a DynamicListBase, and each OrderComment saved itself independently.   Of course you'll need to determine for yourself if thats possible, but usually the larger the object graph the more likely it is things can be broken up that way.

I suggest this because I don't think this feature implies Csla only sending diff-grams back and forth, I suspect it will still be the full object graph, you'll just not have to unbind-rebind the UI.  A diff-gram would require everyone to code to that style on upgrading and it sounds like this merge idea isn't going to require any existing code to be reworked.

If you need the diff-gram approach for performance, I think this thread might be useful: http://forums.lhotka.net/forums/t/9254.aspx

**Comment by GillesBer** [comment]
@ajj7060  Our applications are typical enterprise apps (CRM type), with much more view than update.
With CSLA, we are really able to perform SQL calls when the object is really dirty (usually a specific child of the graph).  Yes, the dynamic list base is a good stereotype that we are now using. We also use a few root objects with a dozen of children: most of the time, only one child is updated, which is very fast.

Without CSLA, the performance were bad because we were performing unnecessary updates.

I was dreaming of diff-grams, but I quickly go through the thread, and I understand that it is difficult to implement all use cases with a diff.
I will have a deeper look to your thread, thanks for sharing.

**Comment by rockfordlhotka** [comment]
This is now being tracked by issue https://github.com/MarimerLLC/csla/issues/712, and I've started working on it.

One thing I'm finding as I start the implementation, is that this will only affect read-write object graphs. I don't plan to merge a new read-only graph into an existing read-only graph at this time. I'm open to discussion on this topic, but it increases the amount of work quite a bit, because right now read-only object graphs don't implement `IParent` - an interface required by my design.

**Comment by rockfordlhotka** [comment]
I just committed the PR for this feature, so it is in master

https://github.com/MarimerLLC/csla/pull/755

There are still some items on the [6.7.100 backlog](https://app.zenhub.com/workspace/o/marimerllc/csla/boards?milestones=4.7.100%232017-08-15&repos=8085749), but I'm considering putting out a beta release just for the in-place merge so people can help test it.

If I did that, would you test and provide feedback within the next couple weeks?

**Comment by Chicagoan2016** [comment]
Something I would like to add ( not sure if it's related to the current discussion), in some of my 'larger' applications I have to call different but related 'Insert' stored procs for the same object. I know we can overload DataPortal_Create, Fetch and Delete methods but could never figure out how to overload Save methods. I understand that it's probably  going against the single responsibility pattern. 
just a thought : )

Regards

**Comment by rockfordlhotka** [comment]
@Chicagoan2016 can you spin that into its own thread?
