### ISSUE TITLE
No Generic IPropertyInfo?

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/cslaforum#352]
Is there any reason why there isn't a `IPropertyInfo<T>` that would inherit from `IPropertyInfo` and that `PropertyInfo<T>` would inherit from? We were looking at this today and it feels like a bit of a gap, and if it was there it would enable a couple of things we're looking at doing. I'm more than happy to add that interface as a PR :), just wanted to run this by people here first to see if there's any technical reason why it can't exist. Given that `DefaultValue` in `IPropertyInfo` is already defined and is of type `object`, that may make it hard to provide a generic version of it....maybe.

**Comment by rockfordlhotka** [comment]
This may or may not work - you'll probably have to try and find out.

iirc correctly, the current design is because I figured out a way to store all the property values in a list without needing to box/unbox the values every time they were accessed. I felt that was important, because I didn't want to incur the boxing penalty on every property access, given that I was developing a scheme to replace the use of private backing fields.

Whether I did the best possible implementation there, I honestly can't say. I came up with an implementation that _worked_.

If you can achieve the goal stated in your post (which makes sense to me) while maintaining the current scheme of strongly typed field values, that would be excellent.

**Comment by Chicagoan2016** [comment]
Hi Jason and Rocky,
I have a question possibly related to this discussion : )
Jason, is your article 
https://magenic.com/thinking/abstractions-in-csla 
 still relevant to the current version of csla?
Since I am supposedly a senior developer :) ( got a few grey hair), a junior developer asked me about dependency injection and CSLA,  sounds familiar? : )

Thanks for your help, you guys are doing an awesome job.

Kind regards

**Comment by JasonBock** [comment]
It is....this is kind of sidetracking this thread so I don't want to talk too much about DI here. But yes, that approach still works, though it's not perfect.
