### ISSUE TITLE
code snippet for 'Criteria' properties

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#431]
Hi All, 
I can't seem to find the code snippet for creating properties inside a 'criteria' object.

regards

**Comment by fujiiface** [comment]
You should be able to just use a regular property if I'm not mistaken.

**Comment by Chicagoan2016** [comment]
When we generate a criteria object using the code snippet ( for creating criteria objects) it also generate a simple property as 

  public static readonly PropertyInfo<int> IdProperty = RegisterProperty<int>(c => c.Id);
            public int Id
            {
                get { return ReadProperty(IdProperty); }
                set { LoadProperty(IdProperty, value); }
            }


but I can't seem to find a code snippet specifically for declaring such properties

regards

**Comment by fujiiface** [comment]
I don't think I've ever used CSLA backing properties for a criteria object since they don't need to have rules checked.  I just make sure the Criteria object is Serializable.

**Comment by jonnybee** [comment]
Correct, there is no snippet provided for this - but it is very easy to create. 

If you only user  Serializable this implies that you are using one of the built-in .NET Binary Serializers to serialize your objects. Be aware tho that some platforms does not provide a binary serializer which is why the MobileFormatter was created.

**Comment by Chicagoan2016** [comment]
thanks @jonnybee  and @fujiiface ,
I modified the snipped for 'read only property with no authorization', I just remove the keyword 'private' before the 'set'.
