### ISSUE TITLE
CSLA .Net for a specific project

### ISSUE THREAD

**Issue by skeeler88** [MarimerLLC/cslaforum#446]
I thought I'd dive deep into the problem without much background. Besides I love CSLA .NET (bought all the books)!!!

I need to consume a XSD and create a UI based off of it (i.e. able to add attributes to an element, complexType, etc.), business rules would be based off of XSD (i.e. minoccur, maxoccur, choice & so forth) so the model has to be dynamic to support N amount of nested child node objects and pretty much anything a XSD supports.

Once the user has completed creating the model from a XSD, I need to export it as a XML to a file that abides by the XSD. The last catch is somehow deserialize a saved XML back into the model.

I need some advice as to how I would approach such a challenge using CSLA .NET? Or would such a project be far out of CSLA .NET scope?

Any advice there on in would be appreciated! I need authorization and authentication so that's why I am trying to think of a approach with CSLA .NET.

Thank you!

**Comment by rockfordlhotka** [comment]
Years ago, when Microsoft was working on the "M" language to create domain-specific languages (DSLs), I experimented with the idea of creating a DSL where you could describe a user scenario with this DSL, and when you compiled the DSL code you'd end up with a complete WPF solution that included a UI, CSLA business layer, and at least a template DAL.

That was fun, but of course Microsoft dropped the M language and Project Oslo, so it never really went anywhere.

But if I understand you, that's what you are asking for here - take a business domain description (your XSD) and use it to generate UI, business layer, and maybe DAL code?

[@tfreitasleal](https://github.com/tfreitasleal) is the better person to answer this in depth, because he wrote and maintains the _CslaCodeGenFork_ code generator.

**Comment by tfreitasleal** [comment]
[CslaGenFork](https://github.com/CslaGenFork/CslaGenFork) consumes an XML file to generate almost everything but the business rules and the UI.

I've thought countless times about UI generation and it's not easy mainly for two reasons:
- specific view details and regeneration (we risk to end up with yet another designer) 
- use what UI techniology?

CslaGenFork generates the code to support the business rules, but the rules must be on a different assembly so CGF's UI can use reflection to show all the constructors and let you choose one, specify the parameters for that constructor, etc

Generate business rules, all kind of business rules isn't easy at all. While we are discussing code generation, you must have a startup reference model (like CSLA) that restricts what can be done - the stereotypes -  and how each stereotype relates to the others, etc,

A small coirrection, I didn't wrote CslaGenFork. The sources have existed for I don't know how long. I just forked the project, updated and made it grow.

**Comment by skeeler88** [comment]
We don't need to generate code based off the XSD we just need a one time setup type of deal. Not trying to create a new approach to the framework. So the UI, DAL would be manually coded and even the BL. 

I guess what I am asking is there somehow I can represent a nested children of themselves within CSLA .NET & a circular dependency (i.e. an element is nested within an element) and can maybe be saved to a NoSQL database or serialized to disc. I think that's the challenge I face with CSLA.NET because I am familiar with the business objects but never had an class be a parent and a child? The hierarchy of the XSD and XML is where I am having the challenge.

That's a little more insight into what I am thinking - it doesn't have to be as dynamic as rocky said.

**Comment by hurcane** [comment]
Here's how I interpret your situation from your latest description:

CSLA and .NET serialization have no problem with handling child collections that are of the same type as the parent. In my business, we work with bills of material. An assembly can contain multiple sub-assemblies, but they are all of the same type.

Circular references (child holding a reference to the parent) are allowed, but they are discouraged because it bloats the data size when serializing the object. Typical approach, when this is needed, is to mark the child's reference to the parent so it is not serialized. The child has a method to "restore" the reference. That method is called from the parent in an override of OnDeserialized.

Writing to and hydrating from XML is a persistence concern. CSLA is persistence-agnostic, which means you have to roll your own persistence logic. You'll have to write the comparison code that translates a class to/from an XML element. You could try to apply some conventions to your business objects so the mapping process can be written in a general way. Perhaps you name your methods and classes to match the element names in the XSD. Or you could apply custom attributes to the classes and properties and use them, through reflection, in the mapping code.

**Comment by skeeler88** [comment]
Thank you everyone. That answers my question.
