### ISSUE TITLE
Probable breaking change to support Netstandard 2.0

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#474]
In this issue I've been working on an issue with NuGet and CSLA and Xamarin/UWP regarding netstandard 2.0

https://github.com/MarimerLLC/csla/issues/793

It is really looking like the only "fix" for this is that CSLA 4.7.100 will _require_ that your projects target netstandard 2.0 (or full .NET 4.0 or 4.5).

This means that if you are currently targeting a pre-FCU version of UWP, or an older version of Xamarin (from current as of late 2017) that you will not be able to use CSLA 4.7.100 - until you upgrade your projects to what is now current Xamarin, UWP, .NET Core, etc.

I am pretty much ready to make this so - particularly because I'm moving from version 4.6 to 4.7 - so it should be easy to understand that this is a pretty major change.

Thoughts?

**Comment by rockfordlhotka** [comment]
**To help the decision and commenting process I'm pushing a prerelease to NuGet with the change**

This should help everyone test to see the real impact of the change.

**Comment by brinawebb** [comment]
This is OK with me! The mobile dev world with Microsoft is getting more and more unified, so a forward-only migration path makes a lot of sense.

**Comment by rockfordlhotka** [comment]
I'm going to take the lack of feedback to indicate that people are fine with this breaking change 😄

**Comment by rockfordlhotka** [comment]
Discovered another snag in this process.

There are just a few parts of CSLA that rely on features of full .NET (.NET CLR). Such as
* COM+ transactions
* Full WCF transport features

There may be a couple others, but those are the big ones.

I'm considering creating a new "CSLA-NetCLR" NuGet package that would continue to include a `Csla.dll` built for full .NET 4.6.1. And the "CSLA-Core" package would _not_ include that, only the netstandard 2.0 assembly.

The result of this, is that people who still need access to COM+ or full WCF (the advanced features not in NS2.0) could choose to migrate to this new "legacy" package. In that case they'd be unable to use the NS2.0 cross-platform features, at least not easily.

Most people, I strongly suspect, can just keep using "CSLA-Core" and switch to NS2.0, becoming cross-platform with no muss or fuss.

**Comment by ajj7060** [comment]
I didn't see this until now.. I'm not entirely sure why .Net 4.6 is considered being dropped or moved to a separate package.  That sounds like it would be pretty bad for us, since we have a WinForms app using full .net 4.6 (a lot of our customers only within the last 1.5 years finished updating to Windows 7), and our Xamarin app which is using the latest.  Both the .Net app and the Xamarin app are using the same business code (shared project, with .Net 4.6 project and a Xamarin project per platform [iOS, Android, UWP]).

We don't have a lot of influence on getting our customer's to upgrade their desktops, it was quite a while before we could get them all to install. Net 4.6.

**Comment by ajj7060** [comment]
Also, a while back (about a year ago) we initially tried to use PCLs for Xamarin, but found that even though our business layer was PCL, because the UI Xamarin project was picking up the platform specific Csla, we got runtime errors due to things missing from the iOS Csla that were defined in the PCL Csla.  Is this essentially the issue?

**Comment by rockfordlhotka** [comment]
@ajj7060 It is important to understand the implications, and I may not have been super clear.

netstandard 2.0 (NS2) is basically like an interface that can be implemented by various flavors of .NET. If you write your code to NS2 then you know your code will run on any flavor of .NET that implements NS2.

NS2 is implemented by
* .NET 4.6.1 and higher
* Xamarin
* UWP (as of Win10 FCU)
* Probably some other platforms too

If you WinForms app is running on .NET 4.6.1, then you can use NS2 assemblies, because .NET 4.6.1 implements NS2. As a result, the NS2 version of `Csla.dll` will work fine for you.

_However_, if you are using things like COM+, or the advanced WCF features not in NS2, then there's a problem.

My current proposal is this:

* CSLA-Core contains the NS2 `Csla.dll`, and all the existing CSLA-* packages depend on CSLA-Core (and thus all rely on NS2. The vast majority of people can use this new NS2 based model and be very happy.
* A new CSLA-CoreClr package will contain the 4.6.1 `Csla.dll` that includes support for COM+, advanced WCF, etc. This will primarily be used in server scenarios where code uses COM+, and perhaps sometimes where advanced WCF features are being used. Advanced WCF does imply that the _client_ is also using .NET 4.6.1 (and the associated CSLA) because obviously the client is also used advanced WCF features to talk to the advanced server WCF endpoint.

The thing I'm still wrestling with, is that this probably also means having a CSLA-WinFormsClr package that targets 4.6.1 - and that would exist _entirely_ because of the advanced WCF requirement.

Yeah, as I'm typing this I can see where doubling the number of NuGet packages is not a good strategy...

Hmm. Perhaps the better strategy is to factor out the COM+ and advanced WCF stuff into their own assemblies, so the _only_ remaining `Csla.dll` is for NS2, and people who use "legacy" features of .NET will need to add the CSLA-COMPlus or CSLA-FullWCF packages to get those features.

That's quite a bit more work for me to make happen, but sounds like the more correct long-term answer here.

**Comment by ajj7060** [comment]
Thanks @rockfordlhotka that explanation does help a bit, and the expansion of the number of Csla-Core packages was a concern for me (since more packages is more work to manage, even with nuget).  My other concern with a NET46 package was it was already being labeled legacy, and that it would have quickly been dropped as "too much of a pain to continue supporting."  So your new approach of just moving the advanced WCF and COM+ to be "add-on" packages sounds much better to me.

My other concern was about the comments in 793 referenced above:  "This is because the Csla.dll used at runtime is set by the app, so that business class library ends up trying to use the platform-specific assembly, not the netstandard assembly. Because these assemblies are not identical, this is a problem."

That sounds exactly like the problem we hit when we first started with Xamarim.  We originally moved our business code to a Shared Project, then created two NET46 projects; one for the client, and one for our server.  The only difference was that the client project didn't include the implementations for the DataPortal_XYZ methods (and some other server only code).  Then we created a PCL to use for all Xamarin iOS and Android (and UWP).  That lead to runtime issues as things were not in the iOS Csla assembly but they were defined by the PCL Csla assembly.  We had to go back and creation iOS, Android and UWP class libraries for our business assemblies to resolve the issue.

So with the work going on in Csla now, I'm wondering where that will leave us for Xamarin; would we suddenly now get the NS20 Csla, which is different from the iOS and cause the issues you're describing?  Or would we be ok?

I tried to investigate a bit on my own, but with the latest VS2017 I have on both computers, both the Shared project and NS20 Xamarin choices have broken templates, and I just get a completely blank solution.

**Comment by rockfordlhotka** [comment]
Xamarin supports NS2.0, as does UWP, and .NET 4.6.1 and higher. That's the point really - NS2.0 is actually providing the dream we had with PCLs - the dream they never really provided.

The only catch is that each concrete platform provides more functionality than is defined by NS2.0. That's not a problem for WPF/WinForms/UWP/Xamarin/ASP.NET because CSLA already provides per-platform assemblies for each of them. 

The problem is with .NET 4.6.1 code that uses COM+ really (and probably some WCF and perhaps some other stuff), because to date that's all been addressed through compiler directives, not a per-platform assembly. 

Regarding your broken Xamarin template issue, I hit that as well. The solution is to 
1. Run the Visual Studio Installer
1. Look on the right side and find the area for mobile development
1. Select the Android SDK 25 option (it isn't selected for some reason)
1. I also selected the Android 25 emulator option
1. Click the modify button to install Android 25

Apparently the new template requires Android 25, but the installer doesn't install it by default. Far from ideal!
