### ISSUE TITLE
Classes vs objects

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#491]
A recent hire asked me why do we say Editable 'objects' and Read-Only 'objects in CSLA and not
say Editable 'Classes'?
I know the difference between classes and objects : ) but I remember Rocky explaining why called his books 'Expert Business Objects' back in early to mid 2000s.
Does anyone remember the explanation?

Best Regards

**Comment by rockfordlhotka** [comment]
Most just because 20 years ago not a whole lot of people _did_ know the difference between classes and object instances, so I used words that conveyed the necessary message at the time.

Academics can get away with forcing the "proper" use of language, but in the commercial education space (where things like tech books live) you need to meet people where they are, not where you with they were 😄

**Comment by Chicagoan2016** [comment]
: )  thanks @rockfordlhotka !
