### ISSUE TITLE
BO class for read only datagrid 

### ISSUE THREAD

**Issue by jayUpadhyay23** [MarimerLLC/cslaforum#499]
I have a read only WPF data grid, so the records in the grid will not be updated from UI instead the grid record will be updated from the code based on certain button click event.

What type of BO should i create for this kind of scenario. Should i create a editable BO and update the properties on button click and then call Save, or should i create a read only BO and do the update using a Command BO. 

Which of the above approach is correct .?

**Comment by tfreitasleal** [comment]
Hi,

In CSLA lingo, "Editable" means "editable by the user". That's why Editable objects support undo, validation and transformation rules, etc.

Let's suppose who want to show the last 20 transactions on some third party application. A Command object is indeed what you need to read the data fom the third party application and update your database (or other kind of storage) and you just need to update the grid every at some time interval.

**Comment by jayUpadhyay23** [comment]
Thanks Tiago for the explaining on this.
