### ISSUE TITLE
Questions about Business rules

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#535]
Hi All,
I am trying brush up on the business rules' implementation by  reading the Business rules chapter of 'Creating objects' ebook. I have a few questions, some of them are confirmations from the kind folks on this forum.

1) If we pass parameters to our business rule class, the first parameter will always be Primary property?

2) Whenever we pass more than one parameters, those parameters (other than the Primary property) should be added to 'RuleUri.AddQueryParameter' ?

3) Calling code can send the required parameters to our business rule constructor, but we decide inside 
     our business rule implementation which one of those parameters are 'InputProperties' and which ones 
     are 'AffectedProperties' ?

4) In order for our business rules to modify properties in the business object, those properties must be passed to the constructor ? and those properties must be added to the 'AffectedProperties'?

5) Primary Property doesn't have to be added to 'AffectedProperties' in order to modify its value by calling 'AddOutValue" ?

Kind regards

**Comment by rockfordlhotka** [comment]
The best 'documentation' for business rules at the moment is the excellent demo created by @jonnybee 

https://github.com/MarimerLLC/csla/tree/master/Samples/NET/cs/BusinessRuleDemo

**Comment by jonnybee** [comment]
1.  Mostly for consistency and readability. In the ctor of the business rule your code may decide to send another property to the base ctor as PrimaryProperty or even set another property as PrimaryProperty but that would make it rather hard to read.
2. Yes -  mostly for input parameters/properties that identifies this as a "separate" rule. The rule engine uses the RuleUri to distinguish which rule has caused this message (and to clear when the rule is no longer failing). You could have the same rule repeatedly on object level or property level and thus the RuleUri must uniquely identify that specific rule.  
3. Yes, your code in the rule ctor must decide on which is Input/Affected. 
4. Yes, if you want to use AddOutValue and get a PropertyHasChanged (as per config Windows/Xaml) when rules have completed. There is overloads of LoadProperty(object, propertyInfo) available in the BusinessRule base class so that you may set a value directly without making the field "dirty". But these also makes it harder to unit test your business rules.
5. Yes, PrimaryProperty is automatically added to AffectedProperties.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka , Thank you @jonnybee
