### ISSUE TITLE
Breaking change to MobileList

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/cslaforum#536]
I want to get an idea of the scope of a potential breaking change I'm proposing. This change is necessary to support webassembly, which requires not depending on `DataContractSerializer` (DCS).

Right now `MobileList` can contain items (type `T`) where T is
1. A primitive type
1. A type implementing `IMobileObject` (so any CSLA type)
1. Any other type that can be serialized by the DCS

My change removes the dependency on the DCS, so the result is that T can be
1. A primitive type
1. A type implementing `IMobileObject` (so any CSLA type)

The question for everyone is this: do you ever create a `MobileList<T>` where T is not primitive or a CSLA type?

**Comment by Chicagoan2016** [comment]
No, I  use it similar to what I post on #534 

Regards

**Comment by rockfordlhotka** [comment]
I did put this change into the preview I'm uploading to NuGet right now (4.7.200 preview).

**Comment by ajj7060** [comment]
Would the change rule out things list List<T>, Hashset<T>, etc?

**Comment by ajj7060** [comment]
I think this sounds fine.  I was thinking this would simplify something we have now, where someone asked me why some code I wrote a year ago declared a `PropertyInfo<MobileList<string>>` and in some classes and in others `PropertyInfo<List<string>>`  

I think the answer is that when I went to use the BO in Xamarin, the `List<T>` didn't work when the MobileFormatter went to serialize it, so I used MobileList and that worked.  This would provide a clear reason; Csla requires everything for a `PropertyInfo<T>` to be a primitive or implement IMobileObject.

I think the Hashsets probably only work because for our main application we use WCF, but the mobile app uses the HttpProxy.  I suspect the classes which use Hashsets probably won't work over the HttpProxy.
