### ISSUE TITLE
Switchable stereotype

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#557]
**Question**
Hi All,
I remember we used to have switchable objects in previous versions of Csla, do we still support this stereotype? and if yes I would like to see a sample.
kind regards

**Version and Platform**
CSLA version: 4.6.603
OS: Windows
Platform: WinForms, WPF

**Comment by jonnybee** [comment]
Do you mean the editable root/child stereotype? 

Basically - it is a business object that has both "root" static Get/New methods and corresponding DataPortal_XYZ methods to get a "root" object and Child DataPortal methods so that it can also be used as a child object. There no special handling in CSLA to support this type of objects so it is more uå to you as a developer/architect to decide on whether you need this type of objects.

**Comment by Chicagoan2016** [comment]
Thank you @jonnybee , I also found a project item template for switchable objects

**Comment by CrossSlide** [comment]
@Chicagoan2016 , where did you find the "a project item template for switchable objects"? Also, how did this work out for you? Thanks

**Comment by Chicagoan2016** [comment]
@CrossSlide ,It's one of the Csla Item templates, you should be able to get them from Nuget.
I ended up not using the switchable stereotypes. If I recall correctly  I had used the switchable objects in Csla around 2006 : ).
@jonnybee  has given an overview of switchable objects above

**Comment by CrossSlide** [comment]
Thanks @Chicagoan2016 !
