### ISSUE TITLE
returning readonlycollection without using LinqObservablecollection

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#577]
Hi All,
I know we have ToSyncList() extension method in Csla. Is there a way we could sort a readonlycollection and return the original readonlycollection? I don't want IEnumerable<T> for obvious reasons but LinqObservableCollection is causing 'unwanted' behavior in UI.

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
You could try just sorting the collection. That won't work with a `BusinessListBase`, because there's a lot going on behind the scenes there. But with a `ReadOnlyListBase` you might be able to do this:

1. Make it read-write
1. Sort the list
1. Make it read-only again

This would need to be done via a method on the collection itself, because the ability to make the list read-write vs read-only is protected.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka
