### ISSUE TITLE
politically incorrect question : ), may be not

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#581]
Hi fellow Csla developers,
I want to know if anyone of us interviewed for a software developer position and having Csla in the skill set helped you get the job? Am I the first one to ask this question? : )

I would personally prefer a developer proficient in Csla over Non-csla guy. I have seen applications (non-trivial) developed without Csla, some of them were horrible, one was good but all the logic was in combination of stored procs, sql functions and views, reflection was used to populate POCOs or datasets.

anyone would like to share their story/experience?

kind regards
**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by ajj7060** [comment]
Yes; at my current job, they were already using Csla and experience with it was required (due to a bad experience with someone not familiar with it then wanting to remove it, which is a non-starter).  There was one other job I applied for in the past which had required Csla experience as well.

In my experience at my current employer, it has been challenging finding existing people which know Csla.  You can find them, but your search will take longer, its not like requiring experience in MVC or WPF.  Of course you can hire someone without Csla experience if you are willing to train them on it, and they are willing to learn.

**Comment by Chicagoan2016** [comment]
Thank you @ajj7060 , One of the reasons I like Csla is, you get a good 'architecture'  for your business applications. I have noticed that it's tough to convince developers with no format training to learn/use Csla. It might be just my experience but I think it was easier to show benefits of Csla to someone with Computer Science/engineering background.

kind regards
