### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by JohnWigger** [MarimerLLC/cslaforum#62]
Hi,
   To understand where I am coming from, I am an experienced .NET developer and CSLA.NET noob.  In the past I have held back from using CSLA due to lack of solid DI support, so I was happy to see that this has been addressed.   I am working with Xamarin on a Mac right now for mobile development.  I am very pleased with all of the effort ongoing with CSLA to support that.
   I have not been able to locate any sort of recent CSLA roadmap.  Is there one?  Has there been recent discussion on projecting js from a .NET business layer?  I have read Rocky's blog post, http://www.lhotka.net/weblog/ProjectingJsCodeFromANETBusinessLayer.aspx from 2013.
  Thanks,
    John

**Comment by rockfordlhotka** [comment]
Thank you for your interest in a roadmap. I have had serious health issues over the past couple years and so the roadmap has largely focused on keeping up with Microsoft and Xamarin as they add features to the underlying platforms.

@JasonBock and some other people did some prototype/research work around a JavaScript/Typescript version of CSLA. At this point that project is on hold because I'm concerned that in the js world we might be a solution looking for a problem more than a solution to existing problems. That world is so unstable I find it hard to imagine building something like CSLA that tends to sit on top of data access and presentation technologies that are at least somewhat stable.


In terms of a roadmap right now, the backlog/issues list is the focus: https://github.com/MarimerLLC/csla/issues

**Comment by JasonBock** [comment]
Yes, the JS/TS attempt is on indefinite hold. I'm watching WebAssembly with interest, though. While that may take time to come to completion, having the ability to use other languages in the browser (and node.js) may be a huge benefit to CSLA in general and make the JS work irrelevant.

**Comment by rockfordlhotka** [comment]
The milestones are also a type of roadmap, though I do need to do a better job of long-term planning with them I suppose.

https://github.com/MarimerLLC/csla/milestones
