### ISSUE TITLE
Creating children 

### ISSUE THREAD

**Issue by kcabral817** [MarimerLLC/cslaforum#628]
I'm using CSLA latest release and trying to add a row with default items to the collection. What I've noticed is the default constructor of the Foo class is called instead of the AddNewCore in the FooList Class. I am unable to get the AddNewCore or the Child_Create methods to get invoked when a new row is added in a XamDataGrid row. (A row is added, but it is from the default constructor of the FooLine Class--i.e. no default values and no MarkAsChild attribute.) Here is the code snippet that is in the 

FooList class: 

    protected override FooItem AddNewCore()
    {
        var item = DataPortal.CreateChild<FooItem>();
        MarkAsChild();
        Add(item);
        return base.AddNewCore();
    }

    protected override void Child_Create()
    {
        base.Child_Create();
        var item = DataPortal.CreateChild<FooItem>();
        MarkAsChild();
        Add(item);
        
    }

I'm using factory classes too and running on the server.  I will need to pass in objects/criteria when constituting the child object.

What am I doing wrong?  If someone has an example on how to do this, many thanks to you!.

**Version and Platform**
CSLA version: 4.7.100
OS: Windows 
Platform:  WPF.

**Comment by rockfordlhotka** [comment]
If I remember correctly (I haven't done WPF for quite a while), the default data grid control does the wrong thing by default, and doesn't use the correct data binding interface. I believe there's a way to handle the grid's event where it wants a new object and provide the object yourself, instead of allowing it to do its default (wrong) behavior of using `new`.
