### ISSUE TITLE
How to remove an item synchronously from DynamicListBase?

### ISSUE THREAD

**Issue by Codelines** [MarimerLLC/cslaforum#65]
When I call the Remove method in a DynamicListBase into a loop, the next step takes place before the asynchronous RemoveItem of the list has been finished. How can I workaround this problem please? Below is an example where ColRelationshipBO is a DynamiListBase:

               ColRelationshipBO col = Relationships.SourceCollection as ColRelationshipBO ;
                for (int i = 0; i < col.Count; i++)
                {
                    RelationshipBO rel = col[i];
                    if (rel.IsSelected)
                    {
                        col.Remove(rel);
                        i -= 1; // here, col.Count remains the same before the Remove and the loop never ends.
                    }
                }

**Comment by rockfordlhotka** [comment]
`DynamicListBase` exists entirely for the purpose of supporting a dynamically edited datagrid in a smart client scenario (Windows Forms or WPF). 

It isn't intended for use via code.

Can you describe the scenario - why are you interacting with the collection via code instead of binding it to a datagrid?

**Comment by Codelines** [comment]
I'm using DynamicListBase as a collection of root objects shown in a WPF listview where I need to add and remove items. Now I've seen that DynamicBindingListBase is synchronous. Is this the base class to use as a root list base in such scenario? Thanks, Lhotka.

**Comment by rockfordlhotka** [comment]
`DynamicBindingListBase` is the same class, but it supports the older Windows Forms data binding instead of XAML data binding.

If you are binding to a listview you should use `BusinessListBase`, that is what it is designed for.

**Comment by Codelines** [comment]
Thanks, Lhotka, but BusinessListBase requires the items to be marked as child. Should I mark the objects as child before insert them and unmark them as child after insertion to have the list behaving like an EditableRootList?

**Comment by ChristopherHlusak** [comment]
I had a situation, in a "batch edit" capability, where I wanted to treat each of the items as a root for purposes of persistence and "self-governance" and yet to be housed in a main root object that might contain some over-arching batch edit rules.

Within the batch edit object (a business base) I have a dynamiclistbase of root objects.  I too wanted them to remain as roots.  The batch edit object handles the item by item persistence of the items of the dynamiclistbase by calling save upon each and potentially having some succeed and some fail.  Clearly this is a bastardization of what dynamiclistbase was created for but it fit what I needed.

As part of the batch edit I wanted to remove clean objects before persisting (and then re-add them when the batch edit came back to the client) so that when batch editing 100 I'm only saving the 2-3 that changed.  I found that what I needed to do is to just create a new dynamiclistbase with the items I wanted to "not-remove", and then I'd load that into the "batch objects" property of the batch edit. 

Anyway, short answer was that I also found it not possible to remove but I did find it perfectly workable to just create a new dynamiclistbase with the objects I wanted not removed.  Not sure if that works in your case.

**Comment by rockfordlhotka** [comment]
In that sort of situation though, you are almost certainly best off creating a subclass from the `Csla.Core` list type(s) that is a more basic list that doesn't bring along all the datagrid-specific behaviors of `DynamicListBase`.

Something somewhat like this:

```c#
  [Serializable()]
  public abstract class BunchOfRootObjectsListBase<T> :
#if ANDROID || IOS || NETFX_CORE
    ExtendedBindingList<T>
#else
    ObservableBindingList<T>
#endif
```

Then you can handle the list changed events in a simpler way and do your own sync/async remove/update operations.

**Comment by ChristopherHlusak** [comment]
Thank you, I hadn't given it much thought as I never use editable root collections except for this scenario.  I adjusted the collection to inherit from ObservableBindingList and it works just fine without the extra gunk.  I imagine I can probably even remove/re-add objects more cleanly if I wanted to refactor now.

**Comment by Codelines** [comment]
Thank you very much Lhotka and ChristopherHlusak, I'll follow the recommendation of Lhotka to solve my problem.
