### ISSUE TITLE
Csla 4.8.1 and PropertyRule Class

### ISSUE THREAD

**Issue by Chicagoan2016** [MarimerLLC/cslaforum#652]
I am implementing a simple business rule in Csla 4.8.1 and inheriting the rule from 'PropertyRule'. The compiler is complaining about the 'Execute' method. "No suitable method found to override".
The signature of the method is
protected override void Execute(RuleContext context)

But If change the parameter type from 'RuleContext' to IRuleContext, the compiler is fine with it.
I know that RuleContext in Csla 4.8.1 implments IRuleContext interface. I wonder why is the compile time error?

Kind Regards

**Version and Platform**
CSLA version: 4.7.100
OS: Windows, Linux, iOS, Android, etc.
Platform: WinForms, WPF, ASP.NET Core, MVC, Xamarin, etc.

**Comment by rockfordlhotka** [comment]
The method signature was changed to require an `IRuleContext`, which is an unfortunate breaking change, and really was my mistake in the first place by using a concrete type rather than an interface.

It does mean that upgrading to 4.8.1 means changing all custom rules so the method signature matches the new signature.

**Comment by Chicagoan2016** [comment]
Thank you @rockfordlhotka
