### ISSUE TITLE
Fluent Validation & CSLA

### ISSUE THREAD

**Issue by kcabral817** [MarimerLLC/cslaforum#665]
I would like to use Fluent Validation (Jeremy Skinner's library) to check business rules.  Is it possible and if so, how can the CSLA brokenrule be integrated?  I've included an example of fluent validation example below.

**Version and Platform**
CSLA version: Latest
OS: Windowsc.
Platform: WPF

public class CustomerValidator: AbstractValidator<Customer> {
  public CustomerValidator() {
    RuleFor(x => x.Surname).NotEmpty();
    RuleFor(x => x.Forename).NotEmpty().WithMessage("Please specify a first name");
    RuleFor(x => x.Discount).NotEqual(0).When(x => x.HasDiscount);
    RuleFor(x => x.Address).Length(20, 250);
    RuleFor(x => x.Postcode).Must(BeAValidPostcode).WithMessage("Please specify a valid postcode");
  }

  private bool BeAValidPostcode(string postcode) {
    // custom postcode validating logic goes here
  }
}

var customer = new Customer();
var validator = new CustomerValidator();
ValidationResult results = validator.Validate(customer);

bool success = results.IsValid;
IList<ValidationFailure> failures = results.Errors;

**Comment by rockfordlhotka** [comment]
I've never looked at this library. From the code you are posting, it looks like the equivalent in CSLA is the code in the `AddBusinessRules` method that you'd write to wire up rule instances to properties.

I rather like that fluent syntax, perhaps CSLA should support something like that, as it does read cleaner than the current approach.

From ProjectTracker's ProjectEdit class:

```c#
    protected override void AddBusinessRules()
    {
      base.AddBusinessRules();
      BusinessRules.AddRule(new Csla.Rules.CommonRules.Required(NameProperty));
      BusinessRules.AddRule(
        new StartDateGTEndDate { 
          PrimaryProperty = StartedProperty, 
          AffectedProperties = { EndedProperty } });
      BusinessRules.AddRule(
        new StartDateGTEndDate { 
          PrimaryProperty = EndedProperty, 
          AffectedProperties = { StartedProperty } });

      BusinessRules.AddRule(
        new Csla.Rules.CommonRules.IsInRole(
          Csla.Rules.AuthorizationActions.WriteProperty, 
          NameProperty, 
          "ProjectManager"));
      BusinessRules.AddRule(new Csla.Rules.CommonRules.IsInRole(Csla.Rules.AuthorizationActions.WriteProperty, StartedProperty, "ProjectManager"));
      BusinessRules.AddRule(new Csla.Rules.CommonRules.IsInRole(Csla.Rules.AuthorizationActions.WriteProperty, EndedProperty, "ProjectManager"));
      BusinessRules.AddRule(new Csla.Rules.CommonRules.IsInRole(Csla.Rules.AuthorizationActions.WriteProperty, DescriptionProperty, "ProjectManager"));
      BusinessRules.AddRule(new NoDuplicateResource { PrimaryProperty = ResourcesProperty });
    }
```

**Comment by jonnybee** [comment]
I've been using FluentValidation (FV) in my current job for almost 3 years in an ASP.NET MVC application (not using CSLA). FV validators validate an entire object (and possibly child objects too). So you could create an object level business rule that detects which validator to use - call that validator and then you map the FV result to CSLA BrokenRules. 

The advantage of CSLA Business Rules is that the will run only the property rules for a given property that was modified by the user when used in a rich client UI such as Windows and Xaml. And note also the  advantages Rocky has already described. FV always validate an entire object and runs all the rules for a given validator (and possible child objects too - depends on the implementation in the validator).

You would also have to override PropertyHasChanged to run the Object level rules as CSLA will only call Object level rules when BusinessRules.CheckRules is called. 

Sample code from ASP.NET MVC: 

    var validator = new CustomerValidator();
    var results = validator.Validate(myCustomerBO);
    foreach (var error in results.Errors)
    {
        //ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
        // Get the PropertyInfo object for each broken propertyName and add to a BrokenRules collection 
    }

Sample Object rule (taken from RuleTutorial sample) that adds broken rules to multiple properties:

    public class ValidateRoot : Csla.Rules.ObjectRule
    {
      public ValidateRoot(IEnumerable<IPropertyInfo> fields)
      {
            AffectedProperties.AddRange(fields);
       }

      protected override void Execute(IRuleContext context)
      {
        var bo = (Csla.Core.BusinessBase) context.Target;
        var name = (string) ReadProperty(context.Target, Root.NameProperty);

        if (string.IsNullOrEmpty(name))
          context.AddErrorResult(NameProperty, "Name is required.");
        else if (name.Length > 50)
          context.AddErrorResult(NameProperty, "Name cannot be longer then 50 chars.");

        var num1 = (int) ReadProperty(context.Target, Root.Num1Property);
        if (num1 < 5)
          context.AddErrorResult(Root.Num1Property, "Num1 must be larger than or equal to 5");
      }
    }

You might even be able to configure a ValidationContext and only validate given property/properties so that it could be used in property rules as well but I have never had the need to go to that level of validation in our apps. But then again the property level rules have additional functionality and configuration for InputProperties/OutputProperties/AffectedProperties that would make it harder to make a generic implementation/integration of FV.

**Comment by kcabral817** [comment]
thank you for your input.  I'm not going to use fluent as that would require another library to add.
