### ISSUE TITLE
Can HttpProxy support synchronous calls?

### ISSUE THREAD

**Issue by coding786** [MarimerLLC/cslaforum#688]
Why all Dataportal client calls( I am using WPF Client) to DataPortalController in ASPNET Core App Server "asynchronous" by default? All the samples with Core App Server shown(with WPF/Windows Client) use async Dataportal CRUD methods to interact with controller. I am getting an exception like "issync ==true" if I am trying to hit DataPortak_Fetch() from wpf cleint(3 -Tier scenario) on a core based app server. 

With a .Net Framework based WCF app server, I was able to make synchronous calls from WPF client.

Is there a way we can use synchronous calls with ASPNET Core app server from a remote client(WPF Client) ? If yes, kindly provide a pointer demonstrating the same

Using ASP.NET Core for hosting app server,
CSLA Pre-release 4.6.9 
Windows

**Comment by rockfordlhotka** [comment]
When I implemented HttpProxy I was unable to figure out a way to handle the sync calls without having a deadlock issue due to the way the UI thread is handled in WinForms and WPF.

I recently may have found a solution though, so I should try it with HttpProxy.

In the meantime, you can try various workarounds. For example, instead of using await on the async call, see if you can get its `.Result` value - that's the fast way to convert an async call to sync. I _think_ that'll lock up the app though, due to the deadlock issue.

The alternate is to wrap the dataportal call in a `Task.Run`, which blocks the UI thread while the data portal is actually invoked on a background thread.

What I think is the real solution is to use this [`AsyncManualResetEvent` concept](https://blogs.msdn.microsoft.com/pfxteam/2012/02/11/building-async-coordination-primitives-part-1-asyncmanualresetevent/) from Stephen Toub. It provides a way for a task to await a lock that isn't really a lock, and so it might offer a way to create a "sync" call that's actually async.

**Comment by coding786** [comment]
Thanks, Please let us know once you roll out a solution for Sync calls with WPF clients. Also, if I continue to use async calls in this scenario, would my Business rules need any code change ? I am thinking how much code refactoring would I need in converting a wpf client + Wcf app server to wpf client + ASPNet Core app server ? 

Also, please confim if the sync calls are supported with Web clients (ASP.NET WebAPIs, ASP.NET Web Applications ) or is there a similar tweak needed there ?

**Comment by coding786** [comment]
hi , can you confirm on my above query ?

**Comment by rockfordlhotka** [comment]
@coding786 you can watch issue 1059

**Comment by rockfordlhotka** [comment]
I have a prototype implementation to have HttpProxy support synchronous calls. You can see the relevant method here: https://github.com/MarimerLLC/csla/blob/33affd0f975d80efe8e6274123f9ae27836a4d8d/Source/Csla.Shared/DataPortalClient/HttpProxy.cs#L413

The trick is that I'm using `Task.Run` to run the async operation on a background thread, while blocking the foreground (UI) thread until it completes.

I think that's fine for WinForms and WPF, but this technique is strongly discouraged for web server scenarios because it can overtax the .NET thread pool. So I suppose a way to put it is that this is fine for low-volume web sites, but not for busy sites.

I'm not sure I want to go forward with this change. If I _knew_ people would only use it from smart clients I wouldn't worry too much, but I fear people may use it from old ASP.NET code (Web Forms, etc.) and run into web server scaling issues.

The only alternative I've been able to discover out there, would be to implement some entirely different http-based proxy class that uses whatever pre-dated HttpClient. Was that WebRequest or something? It has been a long time since I've used anything other than HttpClient.

I do think it is possible to use that older (sync) technology (WebRequest?) to write a synchronous proxy that can talk to the same server endpoint. Maybe that's the better way to go.

Anyone have thoughts on this?

**Comment by rockfordlhotka** [comment]
OK, relative to my previous comment, I did rewrite `HttpProxy` to use `WebClient` in addition to `HttpClient`. This avoids any issues with `Task.Run` - I feel much better now 😉
