### ISSUE TITLE
Csla.DataPortalClient.MobileProxy missing in CSLA 4.9 for .Net

### ISSUE THREAD

**Issue by JacoJordaan** [MarimerLLC/cslaforum#707]
**Question**
The Csla.DataPortalClient.MobileProxy is missing in CSLA 4.9 using .Net framework. Is this by design?

I am inheriting from this class for my own custom proxy and my existing .Net code is not compiling when upgrading to CSLA 4.9. CSLA 4.8.1 is working fine.

4.9.0:
![image](https://user-images.githubusercontent.com/43467554/52905390-4e09b480-3242-11e9-8572-8e0feb218f1f.png)

4.8.1:
![image](https://user-images.githubusercontent.com/43467554/52905394-67126580-3242-11e9-8c25-7510843eeee2.png)

**Version and Platform**
CSLA version: 4.9.000
OS: Windows
Platform: .Net Framework 4.7.2

**Comment by rockfordlhotka** [comment]
This is because the mobile proxy sits on top of WCF and WCF has had limited or no support from modern .NET implementations. As a result I've deprioritized WCF and mobile proxy.

My recommendation is to use HttpProxy, which is supported on all .NET implementations. We've put a lot of work into that proxy/host channel to optimize the use of bandwidth too, so it is generally a win over WCF or MobileProxy.

**Comment by JacoJordaan** [comment]
@rockfordlhotka, I did see that WcfProxy is still available and thought that MobileProxy will also be available for backwards compatibility to full .Net applications.

The only issue I have with the HttpProxy is that it does not support any sync calls. Am I correct on this? If so, is there a way to handle this? 

BTW, enjoyed your first book in CSLA 2019 series. Looking forward to all the others.

**Comment by ajj7060** [comment]
If WcfProxy is going away, will HttpProxy support non-async calls?  We use HttpProxy for our Xamarin apps because its eaiser and you have to (must use async DP calls), but our WinForms app would require ALOT of work to move to async calls, and HttpProxy doesn't (or didn't?) support sync calls.

**Comment by rockfordlhotka** [comment]
I think "going away" is strong wording. I haven't looked recently to see what (if any) parts of WCF exist in .NET Standard, and that's really the gold standard going forward - for Microsoft and CSLA.

So if enough WCF exists in .NET Standard then I'd love to see a new WCF proxy/host channel that sits on that technology.

I'd also like to see HttpProxy support sync calls - just haven't figured out how to do that yet. I'm not 100% sure it is possible in a way that works across all the various UI frameworks (due to the way they handle the UI thread).

**Comment by rockfordlhotka** [comment]
@JacoJordaan WcfProxy still exists _for code running on .NET Framework_. It does not exist for code on any other .NET implementation, because all those other implementations are served by the .NET Standard implementation of CSLA. The .NET Framework is currently an outlier, and exists purely to support legacy code (as in: not .NET Core or Xamarin).

**Comment by JacoJordaan** [comment]
@rockfordlhotka  Thanks Rocky. The performance of MobileProxy is just far far better than WcfProxy - that is the reason I went with MobileProxy in .NET Framework. As it now stands with CSLA 4.9, MobileProxy is not supported and WcfProxy is supported. If it is just a matter of 'putting it back' in again for .Net Framework, then I am sure it will help a lot of people with legacy apps.

**Comment by rockfordlhotka** [comment]
The big difference is that MobileProxy uses MobileFormatter (like HttpProxy), where WcfProxy uses the NetDataContractSerializer. 

We've worked really hard to optimize MobileFormatter for CSLA (which makes sense: it is part of CSLA), and that's the primary reason you see it working so much better.

The real trick, as I mentioned in my reply to @ajj7060 is the underlying transport support in .NET Standard 2.0. For some time the only transport that existed on all .NET implementations was HttpClient - WCF wasn't everywhere. _Maybe_ WCF now exists in .NET Standard 2.0 - I'm not entirely sure to be honest.

**Comment by rob-v** [comment]
I wanted to run CSLA ProjectTracker samples, but they aren't running due to missing MobileProxy. I tried to replace MobileProxy by WcfProxy in WinForms, then I get: 
System.ServiceModel.ProtocolException: 'Content Type application/soap+xml; charset=utf-8 was not supported by service http://ptrackerserver.azurewebsites.net/WcfMobilePortal.svc.  The client and service bindings may be mismatched.'
WebException: The remote server returned an error: (415) Cannot process the message because the content type 'application/soap+xml; charset=utf-8' was not the expected type 'text/xml; charset=utf-8'..

**Comment by rockfordlhotka** [comment]
@rob-v are you trying to run the code out of master, or out of the 4.9 release?

It is absolutely true that the current samples in master may not work, as there are a lot of in-process changes going on in master right now and I won't update the samples until the core codebase settles down.

**Comment by rob-v** [comment]
Ok, thanks, no problem. Out of master, I will try in 4.9 release.

**Comment by rockfordlhotka** [comment]
fwiw, this is why I'm slowly-but-surely migrating everything to the HttpProxy, especially now that it supports both async and sync clients.

It doesn't magically solve all these issues, but it simplifies the protocols used and makes these mismatches less likely.

Of course the _next_ big thing is gRPC, which is coming in .NET Core 3 😄

**Comment by rob-v** [comment]
The issue seems to be update from 4.8.1 to 4.9 for ProjectTracker samples in Jan 2019. When I changed all projects to 4.8.1, I can run it with localhost, still not with azure, but that is fine. I tried to change in WinForms MobileProxy to HttpProxy and it works also. But I guess it still requires 4.8.1 as the localhost uses MobileProxy.
