### ISSUE TITLE
TransactionIsolationLevel compile issue with Xamarin Shared Project

### ISSUE THREAD

**Issue by GreatBarrier86** [MarimerLLC/cslaforum#740]
**Question**
I have a Xamarin solution that consists of the Xamarin Shared Project with the usual Xamarin.iOS and Xamarin.Android projects as well. The Android project has the `ANDROID` compiler variable defined, and the iOS project has the `IOS` variable defined.

I added the Csla.Shared shared project to the solution, and when i did so, I began getting `The type or namespace name TransactionIsolationLevel could not be found (are you missing a using directive or an assembly reference?)` error. I looked at the code and the `TransactionIsolationLevel` enum is wrapped in `#if !NETFX_CORE && !(ANDROID || IOS)`, however, the use of that enum inside `ApplicationContext` and `CslaDataConfiguration` is not, so those classes are unable to find the enum definition, since it's being ignored during compilation.

Shouldn't the references inside `ApplicationContext` and `CslaDataConfiguration` also have that wrapped in `#if !NETFX_CORE && !(ANDROID || IOS)` as well?

You indicated in the post [here](http://www.lhotka.net/weblog/CSLANETVersion46100Release.aspx) that you had concerns you got all the compiler directives right, but it's been a few years, so i wasn't sure if this was related.

**Version and Platform**
CSLA version: 4.9.0
OS: Windows
Platform: Xamarin

**Comment by rockfordlhotka** [comment]
I strongly recommend that you reference CSLA via NuGet rather than building it yourself.

The scenario you are describing hasn't been valid for the past few releases of the framework, as the only valid compile targets are now .NET Standard 2.0, .NET Framework 4.6.1, 4.5, and 4.0. Xamarin support is all provided within the context of .NET Standard 2.0.

**Comment by rockfordlhotka** [comment]
If you feel that you really _must_ build your own DLLs, here are the [instructions to build a CSLA release](https://github.com/MarimerLLC/csla/blob/master/docs/Create-a-CSLA-.NET-release.md) from the docs directory.

You really only need to do steps 1 and 2.ii - all the rest is for updating NuGet and GitHub. The result of 1 and 2.ii is that you'll have a `/bin` directory with all the resulting DLLs just like I create for packaging into NuGet.

**Comment by GreatBarrier86** [comment]
I definitely do not need to build my own. It would just be better if I could debug into your code when issues come up. Stepping through the CSLA source helped me understand how the server side worked when interacting with the proxy. 

If not referencing the source, how do you recommend going about stepping through the CSLA code when issues arise?

**Comment by rockfordlhotka** [comment]
It used to be that I was uploading the code into a symbol source server. Over the years that server apparently stopped being supported and went away. I now believe that github has its own symbol server, but haven't really looked into it.

You are the first to ask about this in a very, very long time, so it has never become a priority...

Basically what needs to happen is some research to figure out what symbol servers are out there now (github? nuget? others?) and to figure out how to upload the source packages to that server as part of my push of the binary packages to NuGet.

**Comment by rockfordlhotka** [comment]
It also occurs to me @GreatBarrier86, that you could also bring in not only the shared project, but also the .NET Standard 2.0 project. Your Xamarin projects could then reference the NS2 project.

The NS2 project is what's built to support Xamarin, and so that's how your Xamarin projects should reference the CSLA codebase. That'll have CSLA building for NS2, which should work fine.

(this is what I do when debugging framework elements)
