### ISSUE TITLE
CSLA, microservices and containers

### ISSUE THREAD

**Issue by michaelblacksm** [MarimerLLC/cslaforum#747]
I hope my questions makes sense and somebody can point me in the right direction as to where to start my research.

Questions: 
1-Can CSLA be used to create microservices to be deployed into containers?

2-Are such projects like a "mini N-tier application" with an ASP.NET Web API project acting as the interface, a regular business library, and the corresponding data access projects (abstract + real implementation)?

3-Is there something special to be made to be able to deploy these applications with containers?

I already read what I could find in this forum. Specifically the thread that contains this reply from Rocky: https://github.com/MarimerLLC/cslaforum/issues/706#issuecomment-465793728

And this other thread: https://github.com/MarimerLLC/cslaforum/issues/78

My background:
I used CSLA around 10 years ago to create a "regular" N Tier application with a Windows Forms UI and later a Web Forms UI.

I have read about microservices and I (hope) understand the ideas behind the concept, but I never built one before.

I read some theories about containers and I understand the advantage, but never used them before.

Thanks in advance for any info you can provide and any suggestion about what to read next.

**Version and Platform**
CSLA version: latest
OS: Windows
Platform: ASP.NET Core

**Comment by rockfordlhotka** [comment]
Let's break this down a bit.

1. You can use CSLA to write code that runs in containers. That code might be a data portal endpoint or a microservice.
1. Hosting a data portal endpoint is easy and powerful, and starting with version 4.9 there are some really cool data portal features for managing versioning, and routing different workloads to specific nodes/pods within a container orchestrator (like Kubernetes)
1. A "microservice" is a standalone application with its own interface (usually JSON), interface control (the web api code), business logic (CSLA object(s)), data access, and data storage
1. You can absolutely implement a microservice where the business layer is one or more business domain objects created with CSLA
1. It is _critical_ to understand that microservices don't share code with each other or with clients!! The whole point of a service is independent versioning, and any shared code is coupling and coupling prevents independent versioning/deployment

What I'm getting at, is that you can use CSLA in containers in two very different ways:

1. Host the data portal just like normal - an n-tier app with your server-side code running in containers (this can be simple or very advanced depending)
1. Use CSLA to create what is typically a 2-tier app _that is a microservice_ (it turns out most microservices are 2-tier: interface/interface control/business layer/data access in one tier, data storage is a separate tier) - it is just that the interface in this case is JSON instead of a GUI or HTML or XAML

**Comment by michaelblacksm** [comment]
Thank you Rocky for your reply, I really appreciate the time that you and other members of the community take to help people like me.

Based on what you wrote I have some other "dump" questions:

1.1- That code that I'll write using CSLA and it will run in containers: Do I have to do something special while coding, or any CSLA application (with all it's layers) is "deployable" into containers as it is? I realize I have to read a lot about containers but I wanted to start coding at the same time. 

1.2- This is a very interesting scenario. I think you wrote more about it in the blog post announcing the release of version 4.9. I'll read it later. Right now I want to start by deploying a microservice.

1.3, 1.4 and 1.5- These matches what I thought about microservices.

2.1- Got it.

2.2- When you write "...a 2-tier app that is a microservice..." do you mean an application with 5 logical tiers that is deployed into 2 physical tiers or literally an application with 2 logical tiers? If it's the later, I don't understand why.

My plan is to start writing a microservice to handle, lets say, Orders. It will be a 5 tier application with a RESTful API with one controller that uses a library project with business objects like OrderEdit, OrderDetailEdit, etc., a DAL project with DTOs and interfaces, and finally the data access implementation, maybe using Entity Framework. There will probably be other microservices to handle Invoices, Customers, etc. Those microservices will not shared any code, not even talk to the same database. Does this sound reasonable?

This last question is not related to CSLA, but I don't want to pass the opportunity to ask to somebody with so much experience: Does microservices should be so specific as to have one for Orders, another for Invoices, another for Payments, etc., or it's also OK to have one for Orders, Invoices and Payments, then another for everything related to Products, Inventory, etc. I mean several related functionality into each of them. I realize that this is not enough information for you to give a decisive answer, but I just one to get an idea of how granular should microservices be.

Thank you again for your help.

**Comment by rockfordlhotka** [comment]
The easiest way to write a service is to create one via ASP.NET Core, in which case you are creating controllers that expose RESTful (or at least RESTish) endpoints. In that project you can reference any NuGet packages that work in the environment, including CSLA.

Starting in VS 2017, if you have Docker for Windows installed, you'll get an option to add Docker support to any new ASP.NET Core project. Nothing else is really required, no.

That said, you should follow good cloud-native practices, such as those at https://12factor.net. Some, like externalizing configuration, are really important.

This all ties into my comment about 2-tier. Yes, I think your apps should always have 5 logical _layers_. I'm just observing that most web sites, and microservices, are deployed to 2 physical tiers, with all the layers running on the web/app server except for data storage, which is usually in PostgreSQL, SQL Server, MongoDB, or something like that.

**Comment by rockfordlhotka** [comment]
Another thing to consider, that I didn't mention in previous posts, is how to transport messages between services. Personally I always recommend using a queued transport, because it is the cheapest and easiest way to get fault tolerance, scalability, reliability, and geo-redundancy. I have a (non-CSLA) example that I use when teaching a workshop on this topic at [VS Live](https://vslive.com).

https://github.com/rockfordlhotka/xplat-netcore-webassembly/tree/master/src/02-services

This demo runs in k8s and uses RabbitMQ for transport within the service-oriented system, and http for external clients (like the browser). Pretty much the basis I think is best.

You can use http of course, but the trick is making http fault tolerant, scalable, reliable, and geo-redundant. Kubernetes can help with this, because the orchestration fabric it provides helps with restarting failed services, having redundant services, IP load balancing, etc. But still, to get reliability you also need to use some retry mechanism on every http call - perhaps with something like [Polly](https://github.com/App-vNext/Polly).

**Comment by michaelblacksm** [comment]
Thank you very much for your responses. I now have a good point to start.
