### ISSUE TITLE
Could not load type 'ApplicationContextManager' from assembly Csla 5.0.1.0

### ISSUE THREAD

**Issue by BlagoCuljak** [MarimerLLC/cslaforum#830]
Hi there, just say that I have moved Dataportal, Buissness and Data access to CSLA5 and EF Core, and so far, so good. Dataportal returns data just fine.

However when I try to connect to DP from my WPF app I get following error i ViewModel:
`TypeLoadException: Could not load type 'ApplicationContextManager' from assembly 'Csla, Version=5.0.1.0,... `

I have follow WPF Project Tracker, added Startup.cs, added DoStartup to my Bootstrapper and it goes to CslaConfiguration.Configure(), and then returns to ViewModel, and then error occurs.

Do you have any suggestions what to do, I have lost entire day on this...

**Version and Platform**
CSLA version: 5.0.1.0
OS: Windows, Linux, iOS, Android, etc.
Platform: WPF

**Comment by rockfordlhotka** [comment]
I'm not sure why this is happening, but I'm pretty sure I can provide a workaround for you to move forward.

You can explicitly provide the context manager via configuration code. It _should_ automatically use the manager from the `Csla.Xaml` assembly, but appears to be trying to load it from the `Csla` assembly, and still failing - so that's confusing.

(assuming the exception you are seeing is a client-side exception, and not a server-side exception?)

In your client startup code you can explicitly set the context manager - which should come from `Csla.Xaml`:

```c#
      CslaConfiguration.Configure().
        ContextManager(new Csla.Xaml.ApplicationContextManager());
```

**Comment by BlagoCuljak** [comment]
Thanks Rocky, had issue with NuGet packets. Seems good so far!
