### ISSUE TITLE
DalManager vs DI

### ISSUE THREAD

**Issue by JacoJordaan** [MarimerLLC/cslaforum#869]
**Question**
With the DalManager you can easily switch between different Dal's with a configuration setting. So, with one compiled application server you can modify the config setting to switch to desired Dal DLL.

With DI I can't figure out a way to do this. Does anybody have some examples how they deal with this issue?

**Version and Platform**
CSLA version: 5.0
OS: Windows, Linux
Platform:  ASP.NET Core

**Comment by rockfordlhotka** [comment]
The selection code moves to `Startup.cs` where the DAL is added to the services collection. Instead of using a `DalManager` things are a little simpler. In the startup code

1. Get the config value
1. Based on the config value, create the correct DAL type
1. Add that type to the services collection

There are various ways to do this, and the methods to add the service to the collection have advanced overloads to make this easier.

**Comment by JacoJordaan** [comment]
Excellent, thanks @rockfordlhotka 

I have opted to add a custom attribute to my Dal classes and used the following code in my `Startup.cs`:
```
           var dalAssemblyName = Configuration["DalAssemblyName"];    //e.g. "DataAccess"    

            var dalAssembly = Assembly.Load(dalAssemblyName);

            var dalTypes = from type in dalAssembly.GetTypes()
                where type.IsDefined(typeof(DalAttribute), false)
                select type;

            foreach (var dalType in dalTypes)
            {
                services.AddTransient(dalType.GetInterface($"I{dalType.Name}"), dalType);
            }
```
My custom attribute class:
```
    [AttributeUsage(AttributeTargets.Class)]
    public class DalAttribute : Attribute
    {
        
    }
```
Usage of the attribute on all of my Dal classes:
```
    [Dal]
    public class PersonDal : IPersonDal
```
