### ISSUE TITLE
Cancelling long running server-side queries

### ISSUE THREAD

**Issue by pssewell21** [MarimerLLC/cslaforum#96]
We have some operations in our software that do some large fetches to our SQL database server.  We are trying to optimize our system and I have been given the task of cancelling long running asynchronous queries that are no longer needed by the UI because of the user closing the window to which the fetch would have returned the data.  I've had success cancelling the async tasks themselves using CancellationToken, but after the request has been serialized and sent to the appserver to get the information from our database, I am unable to cancel it by registering the cancel command as the callback function.  I suspect it is because the appServer boundary exists. So modifying the CancellationToken and calling the callback function on the client side does nothing because the appServer's task is not updated since it was serialized.  Does this sound reasonable? 

So my question: Is it possible to cancel tasks on the appServer so that these long running fetches do not consume unnecessary system resources on our database server?

Fetch from our DataAccess layer:

ReadOnlyListDal.vb:
```vb.Net
Public Function Fetch (ByVal methodName As string, ByVal criteria As Dictionary(Of String, Object), ByVal cancellationToken As CancellationToken) As IDataReader Implements IReadOnlyListDal.Fetch
    Using mgr As ConnectionManager (Of SqlConnection) = ConnectionManager(Of SqlConnection).GetManager("MyDatabaseConnectionString", False)
        Using cmd As SqlCommand = mgr.Connection.Createcommand()
            cmd.CommandText = methodName
            cmd.CommandType = CommandType.StoredProcedure
            cmd.CommandTimeout = cmd.Connection.ConnectionTimeout
            cancellationToken.Register(Sub() cmd.Cancel())

            For Each item As String In criteria.Keys
                cmd.Parameters.AddWithValue(item, criteria(item))
            Next

            Return cmd.ExecuteReader
        End Using
    End Using
End Function
```

**Comment by rockfordlhotka** [comment]
There are two concerns.

First, you need to be able to actually cancel the lowest level operation that's occurring, which you are doing via the `CancellationToken` on the database command object.

Second, you need to be able to indicate that the cancel operation should occur, and I'm not sure how you'd do that across a network boundary (across the data portal).

Data portal hosts are stateless, so each call from the client is isolated from all other client calls (from the same or different clients). This is primarily because we're sitting on top of ASP.NET, which implements this stateless per-request behavior. So it is less of a 'data portal' feature than a feature of ASP.NET/WCF/Web API.

So then the question becomes one of how do you make a second call from your client (where the user clicked Cancel or whatever), to the server, and then on the server be able to interact with the thread that's running the original request you want to cancel.

In the general case this sounds extremely daunting, because you could have a load-balanced cluster of app servers, so the second request might not even route to the same server as the first request.

Even if you only have one app server I'm not entirely sure how you'd defeat the built-in isolation created by ASP.NET/WCF/Web API - isolation designed specifically to prevent the sort of "security hole" you are trying to implement :smile:

**Comment by pssewell21** [comment]
Hello Rocky,

     We have decided that we will no longer pursue completing this task in the way I described.  It would require significant changes to our code, and some of the frameworks we use.  Thanks for taking the time to provide your insight.
